### ISSUE TITLE
Mocha not running Chai tests

### ISSUE THREAD

**Issue by mchorlton** [chaijs/chai#1022]
I'm completely new to Mocha and Chai so this is certainly going to be down to an error on my part but I'd be grateful if anyone could point me in the right direction.

I've installed Mocha and Chai locally with `package.json` file:
```
{
  "name": "myproject",
  "version": "1.0.0",
  "devDependencies": {
    "mocha": "*",
    "chai": "*"
  },
  "scripts": {
    "test": "mocha"
  }
}
```

I've created a sample test file. When I use the Mocha style assert the test runs correctly. When I use the Chai style assert, Mocha outputs `0 passing`. It seems the Chai test is not running.

Sample test file:
``` 
var chai = require('chai');
var assert = chai.assert;    // Using Assert style
assert.typeOf(1, 'number');
```

I'm running the tests using `npm test`.

**Comment by keithamus** [comment]
Hey @mchorlton thanks for the issue.

Mocha requires you to add `describe` and `it` calls to set up your test suite. Take a look at [their docs](http://mochajs.org/#getting-started) and you can see how to compose tests. For example:

```js
var chai = require('chai');
var assert = chai.assert;  // Using Assert style
describe('Number', function() {
    it('is a typeof "number"', function() {
      assert.typeof(1, 'number');
    });
});
```

If you have any other questions of this nature, you should check out Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin, so it's unlikely you'll get a very quick or very thorough answer; Stack Overflow will give you that though.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.
