### ISSUE TITLE
Duplicate subjects in documentation

### ISSUE THREAD

**Issue by netanelben** [chaijs/chai#1026]
`.fail(actual, expected, [message], [operator])` is shown two times.

ref: http://chaijs.com/api/bdd/#method_fail

**Comment by meeber** [comment]
Thanks for the issue @netanelben. I believe these is happening because `.fail` is documented separately in the `expect.js` and `should.js` interface files ([here](https://github.com/chaijs/chai/blob/1ae9386901ee01dffeb1eb377668abc8d510a0f8/lib/chai/interface/expect.js#L12-L24) and [here](https://github.com/chaijs/chai/blob/1ae9386901ee01dffeb1eb377668abc8d510a0f8/lib/chai/interface/should.js#L44-L56)). I think this could be fixed pretty easily by modifying the jsdoc for one of those two, but maybe there's a preferred alternative with the website generation code. @keithamus?

**Comment by keithamus** [comment]
Hey @netanelben thanks for this issue!

Thank you for your time in reporting this. We'll be working on documentation a bunch in chai 5! I'm going to close this, because there is nothing for us to do right now, but rest assured this has been noted, and we'll be making sure to keep this in mind in the future.
