### ISSUE TITLE
Better handling of constructors throwing exceptions

### ISSUE THREAD

**Issue by mevett** [chaijs/chai#1027]
The current release has troubles working with constructors that throw an exception.  Here are several cases all using this class:
<pre>
   class Demo {
        constructor (arg){
            throw new TypeError('demonstration');
        }
    }
</pre>
Case 1:
<pre>
    it("creating a Demo throws an exception", function () {
         expect(new Demo(1)).to.throw();
    });
</pre>
results in
<pre>
TypeError: demonstration
    at new Demo (tests/demo-test.js:9:19)
    at Context.<anonymous> (tests/demo-test.js:14:16)
</pre>
Case 2, Wrapping the use of new in a function:
<pre>
   it("creating a Demo throws an exception", function () {
        var wrapper = function() {
            var bob = new Demo(1);
            return bob;
        }
        expect(wrapper()).to.throw();
    });
</pre> 
results in 
<pre>
TypeError: demonstration
    at new Demo (tests/demo-test.js:9:19)
    at wrapper (tests/demo-test.js:19:23)
    at Context.<anonymous> (tests/demo-test.js:22:16)
</pre>
Case 3, wrapping use of new in a function with its own try/catch:
<pre>
    it("creating a Demo throws an exception", function () {
        var betterWrapper = function() {
            try {
                var bob = new Demo(1);
            }
            catch (e) {
                throw e;
            }
            return bob;
        }
        expect(betterWrapper()).to.throw();
    });
</pre>
results in 
<pre>
TypeError: demonstration
    at new Demo (tests/demo-test.js:9:19)
    at betterWrapper (tests/demo-test.js:28:27)
    at Context.<anonymous> (tests/demo-test.js:35:16)
</pre>
My workaround is to avoid the use of .throws completely:
<pre>
   it("creating a Demo throws an exception", function () {
        var doesThrow = false;
        try{ var b= new Demo(1);}
        catch (e) {
            doesThrow = true;
        }
        expect(doesThrow).to.equal(true);
    });
</pre>

Here's the complete file:

[demo-test.js.zip](https://github.com/chaijs/chai/files/1225928/demo-test.js.zip)

**Comment by keithamus** [comment]
Hey @mevett thanks for the issue.

This one comes up quite a bit; it's a little tricky but here goes:

[Throw](http://chaijs.com/api/bdd/#method_throw) expects a _function name_ so it can _call that function_ - wrapped in a try/catch. Your case 2 attempt is very close, let me just quote your version:

```js
   it("creating a Demo throws an exception", function () {
        var wrapper = function() {
            var bob = new Demo(1);
            return bob;
        }
        expect(wrapper()).to.throw();
    });
```

Now let me show you the version that would work:

```js
   it("creating a Demo throws an exception", function () {
        var wrapper = function() {
            var bob = new Demo(1);
            return bob;
        }
        expect(wrapper).to.throw();
    });
```

The difference there is `expect(wrapper())` vs `expect(wrapper)`. Or to illustrate this as a diff

```diff
@@ -3,5 +3,5 @@
             var bob = new Demo(1);
             return bob;
         }
-        expect(wrapper()).to.throw();
+        expect(wrapper).to.throw();
     });
```

By passing the _function name_ rather than the _result of calling it_ - chai is able to do all the necessary wrapping.

I'll close this issue, as I don't think there is a bug in our code. We've recently rewritten the docs for throw - perhaps could I suggest giving them a thorough re-read and if you can think of any better ways to document this, then please by all means let's continue the conversation in this issue.

**Comment by keithamus** [comment]
By the way, a more succinct way to do this might be to use arrow functions:

```js
expect(() => new Demo(1)).to.throw()
```
