### ISSUE TITLE
expect(Buffer).to.be.a('Buffer') incorrectly fails

### ISSUE THREAD

**Issue by damianb** [chaijs/chai#1028]
As on tin, but best explained by example:

Test case: 

```
	it('should be a buffer', () => {
		let buf = Buffer.alloc(0)

		expect(buf).to.be.a('buffer')
	})
```

result:

```
     AssertionError: expected <Buffer > to be a buffer
```

env is a linux system, with the following:

```
$ node -v
v8.4.0
$ npm ls | grep chai
├─┬ chai@4.1.1
```

**Comment by meeber** [comment]
Thanks for the issue @damianb. Chai's [type-detect](https://github.com/chaijs/type-detect) module is currently classifying Node.js `buffer` objects as the underlying `Uint8Array` due to [these lines](https://github.com/chaijs/type-detect/blob/8fe5aa3cd8f7438a243546dc60049273fead10ab/index.js#L222-L225).

My initial feeling is that `type-detect` should distinguish Node.js `buffer` objects from `Unit8Array`s, especially given the "subtle incompatibilities" between the two documented [here](https://nodejs.org/api/buffer.html#buffer_buffers_and_typedarray). But I don't use either of these very often, so would love to hear some more opinions.

**Comment by shvaikalesh** [comment]
I agree that buffers should be distinguishable: `Uint8Array` may seem like an implementation detail. I guess Node should set `@@toStringTag` to `"Buffer"`.

**Comment by vieiralucas** [comment]
@damianb btw you can workaround this by using the `instanceof` assertion
```js
const buf = Buffer.alloc(0)
chai.expect(buf).to.be.instanceof(Buffer)
```

**Comment by keithamus** [comment]
Hey @damianb thanks for the issue.

We've added this to our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.
