### ISSUE TITLE
Truncate Diff Output

### ISSUE THREAD

**Issue by plasticrake** [chaijs/chai#1055]
When I have diff enabled some of my failures (comparing large arrays) will take up my entire console history. I've had to turn off diff in some cases `chai.config.showDiff = false` I see that `chai.config.truncateThreshold` has no effect on diff output.

I'd like the diff to truncate after certain number of characters or lines.

Not sure if this is a mocha or chai issue. 

Thanks! 😺

**Comment by keithamus** [comment]
Hey @plasticrake thanks for the issue

`truncateThreshold` is used for the error messages (for example `expected [1,2,3] to deep equal [4,5,6]`), lowering the number only affects how these are truncated.

Chai passes `expected` and `actual` properties alongside its assertion failures - it is up to the test runner how to display that info. In other words mocha does the diffing.

I'll close the issue because there's nothing we can do for this. I'd recommend raising an issue on Mocha's tracker. Hope this is helpful 🙂
