### ISSUE TITLE
Prototype should is not added when code run in a new context

### ISSUE THREAD

**Issue by CodeTroopers** [chaijs/chai#1058]
When running the code in a new context, should is not added to the prototype.
This code fail with "Cannot read property 'be' of undefined"

```
const vm = require("vm");

const code = "const chai = require(\"chai\");\n" +
	"chai.should();\n" +
	"const test = \"test\";\n" +
	"test.should.be.equal(\"test\");\n";
vm.runInNewContext(code, { global, require }, { filename: "test.js"});
```

A reproduction is available in [this repository](https://github.com/CodeTroopers/chaiIssue)

**Comment by meeber** [comment]
Disclaimer: I'm not an expert on Node's `VM` module. 

I don't think what you're doing is going to work. Consider this example without Chai:

```js
const vm = require("vm");

Object.prototype.meow = 42;
global.Object.prototype.purr = 43;

console.log('Outer', {}.meow, {}.purr);

const code = "console.log('Inner', {}.meow, {}.purr)\n";
vm.runInNewContext(code, { console, global, require }, { filename: "test.js"});
```

The output is:

> Outer 42 43
> Inner undefined undefined

Even if you move `Object.prototype.meow = 42; global.Object.prototype.purr = 43;` into a separate file, and then require that file from within the sandbox, the inner `console.log` will still display "Inner undefined undefined".

In terms of Chai: Essentially what's happening is that calls to `Object.prototype` inside of Chai's code are referencing the outer `Object` not the inner `Object`. I believe this is due to how `require` works when passed into the sandbox environment.

**Comment by CodeTroopers** [comment]
Ok, effectively and oddly, `require` load the module in the parent context not in the executing context. So the prototype is not modified in the new context.

**Comment by keithamus** [comment]
I think the way we could get this to work (not saying we should) is allow an option on `should()` that applies the `should` to that prototype; e.g. `should({ applyTo: Object.prototype })`.

**Comment by CodeTroopers** [comment]
your option seems clean but i'm not sure it works.

oddly this woks:
```javascript
const vm = require("vm");
const code = "Object.defineProperty(Object.prototype, 'should', {\n" +
	"set: function(value) {}\n" +
	", get: function() {\n" +
	"	return true;\n" +
	"}\n" +
	", configurable: true\n" +
	"});\n" +
	"const test = \"test\";\n" +
	"console.log(test.should)\n";
vm.runInNewContext(code, { console, global }, { filename: "test.js" });
```

but this doesn't work and I don't see what is fundamentally different:
```javascript
const vm = require("vm");
const chai = require("chai");
const code = "chai.should();\n" +
	"const test = \"test\";\n" +
	"console.log(test.should);\n";
vm.runInNewContext(code, { console, global, chai }, { filename: "test.js"});
```

**Comment by meeber** [comment]
@CodeTroopers The difference is that in the second example `chai` is being loaded via `require`. There's a lot of junk happening beneath the surface with `require`, but suffice to say that the code within the `chai` module is carrying along with it the outer `Object.prototype`, even after the `chai` object is passed and referenced inside the new context.

I think @keithamus's solution would work, since it allows the inner context to explicitly pass the `Object.prototype` to Chai.

**Comment by keithamus** [comment]
Hey @CodeTroopers thanks for the issue.

We've added this to our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.
