### ISSUE TITLE
Cannot compare exceptions when thrown in node VM

### ISSUE THREAD

**Issue by 0ortmann** [chaijs/chai#1063]
Chai version: `4.1.2`
Node version: `8.7` (also tried with `8.4` and `7.7.3`)

When an error is thrown from code that is executed within the node VM, I cannot introspect the Error properly.
Consider the following code (reproducible on eg. the node console):
```
var expect = require('chai').expect;
var vm = require('vm');
expect(() => {
    vm.runInNewContext('throw new Error("bam")');
}).to.throw(Error, 'bam');
```
It fails with the error `AssertionError: expected [Function] to throw 'Error' but [Error: bam] was thrown`.

It is possible though, to introspect that something was thrown and then check for its attributes:
```
expect(() => {
    vm.runInNewContext('throw new Error("bam")');
}).to.throw()
  .that.is.a('Error')
  .and.that.has.property('message', 'bam');
```

I would expect that chai can handle / inspect errors correctly, when thrown inside a VM context.

**Comment by meeber** [comment]
@0ortmann Thanks for the issue. So the problem (in non-Chai terms) is essentially this:

```js
try {
  throw new Error("bam");
} catch (err) {
  console.log("one", err instanceof Error);
}

try {
  vm.runInNewContext('throw new Error("bam")');
} catch (err) {
  console.log("two", err instanceof Error);
}
```

> one true
> two false

Your first example is failing because the engine itself is reporting that the thrown error isn't an instance of `Error` (at least not the same `Error` constructor that's available in the outer context).

The `.is.a('Error')` in your second example is using the `type-detect` module [here](https://github.com/chaijs/type-detect/blob/e10c4e5e09897ea43d93fe5cc8e4da20d8a360b3/index.js#L363-L367) to guess the object's type, instead of using `instanceof`, which is why it passes.

`.throw` is purposefully using `instanceof` instead of type-detection; this is what allows someone (for example) to provide `TypeError` as the first argument to see if the thrown error is a `TypeError`.

I'm not sure if this problem is fixable by Chai.

**Comment by 0ortmann** [comment]
Thanks for your feedback! Closing.

**Comment by 0ortmann** [comment]
As a follow up in case somebody is interested -- Pass the `Error` constructor into the VM context, like so:
```
vm.runInNewContext('throw new Error("bam")', {Error: Error})
```
Then the same constructor is used inside and outside the VM. Thus a successful `instanceof` check is possible.
