### ISSUE TITLE
Proposal, use opencollective-cli

### ISSUE THREAD

**Issue by brutalcrozt** [chaijs/chai#1072]
When use [opencollective-cli](https://github.com/opencollective/opencollective-cli) we can have :
-  post-install donate message, after user install chai via cli.

I am curious about others opinion about this. :smile:

**Comment by meeber** [comment]
Thanks @brutalcrozt. l'll defer to the others on this topic!

**Comment by keithamus** [comment]
I am personally against us using post-install scripts. It's a good way to annoy folks who use our projects. Babel tried this to help users and got a lot of negative feedback around this. If people want to donate, they can - but a lot of us are unable to accept money due to conflicts with our jobs, so donations can only go on small sundries like stickers. We have enough donations for stickers, so there is little incentive to get more donations!
