### ISSUE TITLE
`deep.include` fails deep equal arrays

### ISSUE THREAD

**Issue by javinor** [chaijs/chai#1081]
This fails (!?):
```
expect([{a:7}]).to.deep.include([{a:7}])
```
but this passes:
```
expect([{a:7}]).to.deep.include({a:7})
```
This passes too:
```
expect({a:7}).to.deep.include({a:7})
```

Is this the expected behavior?

**Comment by meeber** [comment]
Hi @javinor. Yup, the examples you provided are in accordance with the documented behavior, particularly [these lines](https://github.com/chaijs/chai/blob/6e9bfc1329f79fa25c7c60fc801a405e5c2ca077/lib/chai/core/assertions.js#L322-L330).

The first example fails because it's looking inside of the target array for an element that deep equals `[{a:7}]`. The only element inside of the target array is `{a:7}`, which doesn't deep equal `[{a:7}]`.

**Comment by javinor** [comment]
Thanks for the quick reply! 
I was trying to do a more verbose version of:
```
expect(['foo', {a:7, b:7}]).to.deep.include(['foo', {a:7}]
```
without taking apart my data structure. Is there another way that I missed?

**Comment by keithamus** [comment]
@javinor you probably want to make those two assertions independantly;

```js
expect(['foo', {a:7, b:7}]).to.include('foo').and.deep.include({a:7, b: 7})
```

If you need to assert that a subset is included, something like `expect([{ a: 7, b: 7 }]).to.include({ a: 7 })`, as far as I recall that is not possible currently - although someone might have an idea.

**Comment by javinor** [comment]
@keithamus thanks! My real scenario is a bit too complex. I'll try and see if I have an idea for a plugin and a simpler way to make it work.
