### ISSUE TITLE
SetState

### ISSUE THREAD

**Issue by Ahershel** [chaijs/chai#1087]
Hi, can i set component local state using chai? or do i have to use enzyme?
right now i'm only using mocha and chai to unit test a component.

sorry for the dumb question, i'm still new in react especially testing..

**Comment by keithamus** [comment]
Hey @Ahershel thanks for the issue.

I'm not really sure what you're asking here I'm afraid. But chai comes with nothing specific to react, so chai enzyme is probably your best bet.

I will say though, you'd have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.

**Comment by Ahershel** [comment]
thanks for the answer, i have a problem with stackoverflow, i type the same question like i type here but it wont get post, it says my post didn't meet their body standard question. cant even type "chai" there

what i mean is, when i test my component, i need to set local component state before expect something, and can it be done using only chai?

`beforeEach(() => {
    let state = {...dummy_warehouse};
    component = renderComponent(WarehouseList, null, state);
   //i need something like this : component.setState({permit: true});
  });

  it('show the title, new item button and search form correctly', () => {
    expect(component.find('h1').text()).to.equal('warehouse list');
    expect(component.find('#id_new_warehouse')).to.exist;
    expect(component.find('#id_search_key_warehouse')).to.exist;
  });`

**Comment by keithamus** [comment]
@Ahershel I would recommend taking that code example over to stack overflow and asking. It's worth taking the time to write a well-formatted question as you'll get much better answers there.
