### ISSUE TITLE
Show property name in property that assertion error message

### ISSUE THREAD

**Issue by peteranny** [chaijs/chai#1089]
Given:

```
const myProps = { myNumber: 'myWrongTypeNumber' }
expect(myProps).to.have.property('myNumber').that.is.a('number')
```

Which throws:

```
AssertionError: expected 'myWrongTypeNumber' to be a number
```

Hope this could be something like

```
AssertionError: expected 'myWrongTypeNumber' in property 'myNumber' to be a number
```

**Comment by brutalcrozt** [comment]
Why it should be on one statement? I would have 2 statement, 1 for the property and 1 for the type.
Let's hear the opinion of the others as well.

**Comment by peteranny** [comment]
I thought so too

But now that such API “.that” is provided, doesnt users who use it intend to identify “which” property is wrong or not?
Therefore, I think it is reasonable to include the property name in the assertion when “.that” is used.

**Comment by keithamus** [comment]
Hey @peteranny thanks for the issue!

We have plans to improve error messaging, around chai version 5 we should see a completely new system for error messages which should do exactly what you want. I'll close this because its something on the horizon - we just need to [get all our ducks in a row](http://www.dictionary.com/browse/get-one-s-ducks-in-a-row) first.

**Comment by keithamus** [comment]
Oh and - https://github.com/chaijs/chai/issues/457 is our roadmap issue. You can track progress on v5 thetre.
