### ISSUE TITLE
Assert, getter function always fail with expecting a property

### ISSUE THREAD

**Issue by brutalcrozt** [chaijs/chai#1090]
For the reproduction shake only `assert.decreasesBy`. See [reproduction](https://runkit.com/adi/5a1004fa78a60300129325fa), line 16 pass; 18, 19 both fail.
> AssertionError: 1: expected [Function: fn] to have property 'x'

But i suspecting:
- assert.decreasesButNotBy
- assert.increasesBy
- assert.increasesButNotBy

When use getter function, let me know if i am wrong.
Discovered when made #1085 to aim #1084.

**Comment by brutalcrozt** [comment]
It not feel right when expecting function to have property `x`. It do make sense when expecting object to have property `x`.

Any though @meeber , somehow expecting hope from you. Hopefully i mention on right time.

**Comment by keithamus** [comment]
Hey @brutalcrozt thanks for the issue.

You're right, it is an awkward error message. We could perhaps look at improving this by adding an error message if you mix the arguments around. I'd be happy to see a PR of this nature!

**Comment by brutalcrozt** [comment]
Assign me Cap, working on it.

I have a question, the 3rd param was written `optional` but when we use the `getterFn` i feel like need to have the 3rd param.
Then [here](https://github.com/chaijs/chai/blob/master/lib/chai/interface/assert.js#L2760) still need 4th param `delta`.  I found it awkward when we use `assert(fn, getterFn, null, 1)` for example. The 3rd param `property` as optional also found on several function, any advice?

**Comment by keithamus** [comment]
It looks like you just need to throw when `getterFn` returns a number, while property and delta are supplied, right?

**Comment by lucasfcosta** [comment]
Hey folks, I'm not sure about the cases that are valid to throw here.

What if we have a property in a function that we want to check instead of running it?

This is a valid use-case and this is IMO what people would expect these assertions to do.

For example:

```js
function myBook() {};
myBook.value = 10

function lowerValue() {
  myBook.value -= 1
}

assert.decreasesBy(lowerValue, myBook, 'value', 1);
```

This should not throw right?

However, whenever a property name is not provided I see no problem in running the second argument if it is a function.

**Comment by brutalcrozt** [comment]
Yet i am not trying throw anything.
> This should not throw right?

It will fail with `AssertionError: 1: expected undefined to be a number.` I just inline it on test

I just questioning what's documented, i don't have any appropriate step to take.
nit: [delta](https://runkit.com/adi/5a13f56b1601820012331be9) documented number, looks like string still pass. I just noticed, no offense. But when we found better options it will be great i guest.

Now i am confused, should discuss on issue or related PR then. I will follow any response i for now.
I mention on PR [comment](https://github.com/chaijs/chai/pull/1085#issuecomment-346030435), awaiting review and help regarding refactor `tmpMsg`

**Comment by brutalcrozt** [comment]
Recently i found that this is invalid, but still have things to discuss.

Hopefully i pick the word correctly. I refer the bdd style function signature, which is look good to me.
<details><summary>bdd decrease</summary>

![bdd decrease](https://user-images.githubusercontent.com/3001652/34072551-ddad5574-e2bb-11e7-86f1-f6b684c12397.PNG)

</details>

**Highlight:** (I mean by convention) Order matter, and required parameter on the left. Optional parameters on the right and are **grouped**.

Now let's look on tdd / assert interface: 
<details><summary>decreases</summary>

![decreases](https://user-images.githubusercontent.com/3001652/34072553-ed9d1fc8-e2bb-11e7-961d-8a96d98ace17.PNG)

also found on doesNotDecrease, plus the negation increases (2 things). Some parameter not in the group of optional parameter.
</details>
We read from top to bottom. The function signature (the first line) really matter, that is the first thing we read. Personally when i already get the point from first line, i stop reading an continue to write the code.

<br><br>
I see deeper violation
<details><summary>decreasesBy</summary>

![decreasesby](https://user-images.githubusercontent.com/3001652/34072555-f3fc785a-e2bb-11e7-8f9c-6b568d0b4f6e.PNG)
also found on doesNotDecreaseBy, decreasesButNotBy. I am not check the increases yet, but it seems worth doing.

Some required parameter are placed between optional parameter.
</details>

Sure bdd and tdd (assert) is entirely different concept, and we use different approach. We take bdd with chainable method, but i am not sure with assert interface. My point just to make improvement. I will be happy to hear feedback or even pointing my misunderstanding.

**Comment by lucasfcosta** [comment]
Since me and @keithamus are cleaning up issues I’ll close this because it will go into the roadmap.

As I demonstrated before, asserting on properties of functions is a valid use case.

I also mentioned that we can actually see if users did pass a property name or not by checking the number of arguments. If users pass 3 arguments then it means the third one is a value, not a property name (after all `decreasesBy` implies you will have to pass an argument which tells the delta). **So this is what we’re going to do**.

**Comment by lucasfcosta** [comment]
Since me and @keithamus are cleaning up issues I’ll close this because it will go into the roadmap.

As I demonstrated before, asserting on properties of functions is a valid use case.

I also mentioned that we can actually see if users did pass a property name or not by checking the number of arguments. If users pass 3 arguments then it means the third one is a value, not a property name (after all `decreasesBy` implies you will have to pass an argument which tells the delta). **So this is what we’re going to do**.
