### ISSUE TITLE
Prototype function isn't recognized with testing with Chai

### ISSUE THREAD

**Issue by InezWijker** [chaijs/chai#1093]
I have a method **Element.prototype.collidesWithOneOf**. I am testing with assert.isTrue and assert.isFalse (chai.assert). 
objectElement is a variable I have declared which contains an object and represents an Element: 
_var objectElement = {radius: 20, x: 170, y: 190, color: "Olive"},_
_arrayElement1 = [{radius: 20, x: 170, y: 190, color: "Olive"}, {radius: 20, x: 130, y: 150, color: "Olive"}];_
_(assert.isTrue(objectElement.collidesWithOneOf(arrayElement1), "")_

I want to test this function but I get an error:
TypeError: objectElement.collidesWithOneOf is not a function.

What must I change in the test script to make sure this prototype function is recognized?

Is there anyone who can help me with that?

**Comment by lucasfcosta** [comment]
Hi @InezWijker, thanks for your issue! 😄 

As the error itself states, `collidesWithOneOf` is not a function present in `objectElement` so it cannot be called. Probably, this property on the `objectElement` is `undefined`.

Given this I can suggest you the following options:
1. Check that `collidesWithOneOf` has really been defined on `Element.prototype`
2. Check if `objectElement`'s prototype to make sure it "inherits" from `Element.prototype`
3. If you've done all the above, look for typos, that will be probably it.

Since this is not an issue related to Chai itself, I'm going to close it for now.

But please, do leave a comment if you have any further doubts and I'll be more than happy to help :)
