### ISSUE TITLE
'equal' for immutable.Map with arrays as a value in entries

### ISSUE THREAD

**Issue by IgnatovDan** [chaijs/chai#1102]
It seems that 'equal' works incorrectly for Map objects that contain arrays as a value in entries:

```
import { List, Map } from 'immutable';
import { expect } from 'chai';
import chai from 'chai';
import chaiImmutable from 'chai-immutable';
chai.use(chaiImmutable);

describe('equal_Map', () => {
    it.only('equal_Map_EntryIsArray_1', () => {
        const map1 = Map({e1: [`1`]});
        const map2 = Map({e1: ['1']});
        expect(map1).to.equal(map2);
    });
});
```
Results:
       equal_Map_EntryIsArray_1:
      AssertionError: expected 'Map { "e1": 1 }' to equal 'Map { "e1": 1 }'

To avoid it, I changed Array to List and Map objects with these values are 'equal':

```
    it.only('equal_Map_EntryIsList_1', () => {
        const map1 = Map({e1: List([`1`])});
        const map2 = Map({e1: List(['1'])});
        expect(map1).to.equal(map2);
    });
```
Results:
√ equal_Map_EntryIsList_1

Is this a correct approach?

**Comment by lucasfcosta** [comment]
Hi @IgnatovDan, thanks for  your issue! 😄 

TBH I don't know much about `Immutable`, but here is what I found out.

This is the comparison that `chai-immutable` does when comparing those two values:
https://github.com/astorije/chai-immutable/blob/42abdaab88f8fb4e2bc3b980f3b2240cf5814fdb/chai-immutable.js#L98

And here are the docs for `Immutable.is`:
https://facebook.github.io/immutable-js/docs/#/is

Having mentioned that, it seems that whenever this assertion fails it is due to the call to `Immutable.is` returning a falsy value when the passed object is an iterable, otherwise it will just do a strict (`===`) comparison.

[Here is the code for `is`](https://github.com/facebook/immutable-js/blob/master/src/is.js). As you can see in [this line](https://github.com/facebook/immutable-js/blob/master/src/is.js#L87) it calls the `equals` method implemented in the objects [if the value is considered to be an object (which happens when the object implements `equals` and `hashCode`)](https://github.com/facebook/immutable-js/blob/master/src/Predicates.js#L36).

Having said that, I think you should take a look at [the `equals` method used by `Map`, which comes from this mixin](https://github.com/facebook/immutable-js/blob/4b695f1f0210fa5f27d2111bad44327732e7019d/src/CollectionImpl.js#L316).

That method uses [Immutable's own `deepEqual` implementation](https://github.com/facebook/immutable-js/blob/4b695f1f0210fa5f27d2111bad44327732e7019d/src/utils/deepEqual.js), which is the method that is returning you false on this comparison.

In that method we get to [this line](https://github.com/facebook/immutable-js/blob/master/src/utils/deepEqual.js#L72), which calls `is` again for each one values we've found (this works recursively).

Finally, [getting back to `is`](https://github.com/facebook/immutable-js/blob/4b695f1f0210fa5f27d2111bad44327732e7019d/src/is.js) we can see that when arrays are passed in they do not enter any conditional branches and end up getting to [this line](https://github.com/facebook/immutable-js/blob/4b695f1f0210fa5f27d2111bad44327732e7019d/src/is.js#L84), which returns false since [an `array` returns false when it is passed to `isValueObject`](https://github.com/facebook/immutable-js/blob/master/src/Predicates.js#L36) due to not implementing `equals` and `hashCode`.

Having said that I think that you should open an issue on `Immutable` if you want arrays to start being recursively (`deeply`) compared, because that's the ultimate source of truth that `chai-immutable` uses (after all that's the library it is built on top of).

Please let me know if you need any further help. If your issue on `Immutable` happens to be accepted I'm also more than happy to submit a PR there introducing this change.

**Comment by casperOne** [comment]
It doesn't work incorrectly.

From the documentation for `is`:

> Value equality check with semantics similar to `Object.is`, but treats Immutable `Collections` as values, equal if the second `Collection` includes equivalent values.

The design error here is that you are including a mutable object (the array) in what is essentially an immutable value (the map, also, arrays are not `Collection` instances so they are compared by reference).

What you want to do is set `e1` to [`List`](https://facebook.github.io/immutable-js/docs/#/List) instances, and then `is` should return `true`.

**Comment by meeber** [comment]
It sounds like this issue was adequately explained, and it hasn't been updated in awhile, so I'm gonna go ahead and close it. Feel free to reopen as needed.
