### ISSUE TITLE
Chaining lengthOf and within not working

### ISSUE THREAD

**Issue by frauss** [chaijs/chai#1105]
I suspect I'm doing something dumb but I'm trying to chain together lengthOf and within assertions to make sure an array in an object is of length 0 or 1.

This test works properly:

`
expect(responseObject.KeystoneResponse.IncludeEntitlements.length).to.be.within(0, 1);
`

but this test throws an exception:

`
expect(responseObject.KeystoneResponse.IncludeEntitlements).to.have.lengthOf.within(0, 1);
`

the exception is:

`
TypeError: expect(...).to.have.lengthOf.within is not a function
    at LambdaTester.event.expectResult.result (test/handlers/entitlementsHandler.Test.js:79:94)
    at runVerifier (node_modules/lambda-tester/lib/runner.js:176:16)
    at waitForXRay.then (node_modules/lambda-tester/lib/runner.js:276:32)
    at process._tickCallback (internal/process/next_tick.js:109:7)
`

any idea what the problem might be?

Fred

**Comment by lucasfcosta** [comment]
Hi Fred (@frauss), thanks for your issue!

Due to the stack trace you have provided I suspect your error has something to deal with your test runner, I cannot confirm, however.

I just tried to reproduce your error with the following test, but I have not been able to do that:

```js
it.only('within', function() {
  expect([3]).to.have.lengthOf.within(0, 1);
});
```

Can you please provide us the version of Chai you are using and a minimum reproducible test-case as well?

**Comment by frauss** [comment]
It certainly appears to be environmental as I cut and past your test into my test file and it also blows up. 

I am using Chai V4.1.2 and as far as I can tell Mocha 4.0.1. 

I'll close this for now as I can certainly work around this and will continue to muck about till I can get to the bottom of it.
