### ISSUE TITLE
Avoid CHAI stop his execution

### ISSUE THREAD

**Issue by simone989** [chaijs/chai#1106]
I'm writing my unit test with an http request.
I want to test different fields in response but when I check fields in the first exception CHAI closes all, single test too. I want that CHAI continues his test execution.
How can I do this?

This is an a example how to use the expect.

`expect(res.body.data.user_data,"last_name").have.property('last_name');
expect(res.body.data.user_data.last_name,"last_name").be.a('number');`

`expect(res.body.data.user_data,"username").have.property('username');
expect(res.body.data.user_data.username,"username").be.a('string');`

**Comment by meeber** [comment]
Hi @simone989. I'm not fully understanding the problem. Are you saying that if the first assertions (regarding "last_name") fails, you want the second assertions (regarding "username") to still be performed? If so, this problem is more about how you organize your tests to be executed by your test runner (as opposed to what Chai does or doesn't do as an Assertion Library).

For example, if you're using Mocha, you could perform the http request in a `before` block and then perform multiple assertions on the response within separate `it` blocks:

```js
describe("my http request response", function () {
  let res;
  before(function () {
    res = fnThatReturnsHttpRequestResult();
    return res; // Assuming res is a Promise, returning it tells Mocha to wait until it resolves
  });
  it("contains a numeric last_name property in the user data", function () {
    expect(res.body.data.user_data,"last_name").have.property('last_name'); 
    expect(res.body.data.user_data.last_name,"last_name").be.a('number');
  });
  it("contains a string username property in the user data", function () {
    expect(res.body.data.user_data,"username").have.property('username'); 
    expect(res.body.data.user_data.username,"username").be.a('string');
  });
});
```

There are other ways to go about this.

**Comment by meeber** [comment]
I'm going to go ahead and close this issue since it hasn't been updated in awhile. Feel free to reopen as needed.
