### ISSUE TITLE
Support checking the prototype of objects

### ISSUE THREAD

**Issue by Radiergummi** [chaijs/chai#1114]
Using ES6 classes a lot, I often construct more complex inheritance chains. At some point, I want to make sure children classes actually extend some parent class. As far as I've seen, there is no way to determine whether an object is the prototype of another.  
It would be great to have core methods available for that: 

```js
class Foo {}
class Bar extends Foo {}
class Quz extends Bar {}

expect(Bar).to.extend(Foo);
expect(Quz).to.inheritFrom(Foo);
expect(Foo).to.be.prototypeOf(Bar);
expect(Foo).to.not.be.prototypeOf(Quz);
```
The `inheritFrom` assertion would be most useful as `Quz` does not directly extend `Foo` but still inherits from it, that is a little awkward to test otherwise.  
I know you could just check for an inherited method, but chances are that the child class does define (or overwrite) that method by itself.

I feel like especially the last one should be part of Chai itself. For now I'm using `expect(Foo.isPrototypeOf(Bar)).to.be.true` but I wanted to leave this as a feature request.

**Comment by meeber** [comment]
@Radiergummi I like the idea of there being an assertion that works directly on constructor functions / classes for testing inheritance. As you noted, a workaround is to use `isPrototypeOf` manually. Another workaround is to test an instance instead of the actual constructor:

```js
expect(new Quz()).to.be.an.instanceof(Foo);                                   
expect(new Quz()).to.be.an.instanceof(Bar);                                   
expect(new Quz()).to.be.an.instanceof(Quz);
```
It'd be neat not to have to use workarounds for this. I like `.prototypeOf` and `.extend`, although I prefer `.inherit` over `inheritFrom`. My feeling is that `.extend` and `.inherit` should be aliases of the same assertion; in other words, `.extend` would pass even if the class doesn't directly extend the parent.

Pinging @chaijs/chai for more discussion before tagging this as PR wanted.

**Comment by keithamus** [comment]
I would be happy to simply oveload `instanceof` so that it accepted constructors. I would also be happy with a `.extend`/`.extends` assertion instead.

**Comment by Radiergummi** [comment]
@meeber would you see any use for an assertion checking for direct inheritance? While I'd be happy with `.extend`, there are some situations I would like to check immediate parent classes too.  
@keithamus overloading `instanceof` to accept constructors seems to be problematic from a grammar point of view, but as a foreigner I might be wrong here...

**Comment by meeber** [comment]
I'd prefer to have a separate assertion for this rather than overloading `instanceof`.

Regarding direct/indirect inheritance, the options seem to be:

1) Have two separate assertions: `.extend` (which allows direct inheritance only) and `.inherit` (which allows direct and indirect inheritance)
2) Have a single aliased assertion with an optional flag: `.extend` and `.inherit` both allow direct and indirect inheritance unless the `directly` flag is set (e.g., `.directly.extend` and `directly.inherit`), in which case only direct inheritance is allowed.

I'm leaning toward the second option, but haven't formed a strong opinion yet.
