### ISSUE TITLE
fn is not a function

### ISSUE THREAD

**Issue by basherr** [chaijs/chai#1121]
I've simple test that is as  follows
```
// abc.test.ts
const Client = require('node-rest-client').Client;
import Nightmare from "nightmare";
import * as chai from "chai";
import chaiString from "chai-string";
chai.use(chaiString);  
//node_modules\chai\lib\chai.js:39
//    fn(exports, util);
//   ^
// TypeError: fn is not a function
```
The `npm` command is as follows
`mocha --recursive --require jsdom-global/register --require ts-node/register --require babel-core/register tests/domains/*`

**Comment by basherr** [comment]
closing as `chai` works with `require` statement.

**Comment by gary1410** [comment]
What's your solution here - I'm getting the same error too, but there needs to be a better way to than to use require if all your code is es6.

**Comment by meeber** [comment]
@gary1410 It's difficult to troubleshoot OP's issue because they're using a couple of transpilers. What I can tell you is that "TypeError: fn is not a function" is saying that the value being passed to `chai.use()` isn't a function, suggesting that the problem is related to `import chaiString from "chai-string";` (as opposed to the Chai import). However, the below example (with no transpilers) works fine for me when running `node --experimental-modules` with Chai@4.1.2, so I dunno. I'd guess OP's issue is related to transpiling.

```js
import chai from "chai";
import chaiString from "chai-string";

chai.use(chaiString);

chai.expect("blah").to.startWith("bl"); // Passes
chai.expect("blah").to.startWith("xl"); // Throws AssertionError
```

**Comment by jasonswearingen** [comment]
@meeber posts the solution.   specifically, if you are using ```es-module``` style imports you **MUST** call chai things like:

```typescript
//works
import chai from "chai";
import chaiString from "chai-string";

//does not work
import * as chai from "chai";
import * as chaiString from "chai-string";
```

**Comment by nilsreichardt** [comment]
This is also working for me:
```ts
import chai = require("chai");
import chaiAsPromised = require("chai-as-promised");
chai.use(chaiAsPromised);
```
