### ISSUE TITLE
assert.isNull on HTML Element results in circular JSON.stringify error

### ISSUE THREAD

**Issue by mhchen** [chaijs/chai#1136]
I'm using chai in a browser integration test. Calling `assert.isNull(document.querySelector(.foo'))` when `.foo` is present in the DOM results in the following unhelpful error message:

```
        TypeError: Converting circular structure to JSON
            at JSON.stringify (<anonymous>)
```

It seems that this is from chai attempting to log the element to console. Since the element has circular references, this error results.

1. Is there a better API for asserting that a DOM node is present or not?
2. If not, would you be open to a PR that avoids circular references when attempting to print the element to console using `JSON.stringify`?

**Comment by meeber** [comment]
@mhchen I've never used it, but might be worth checking out https://github.com/nathanboktae/chai-dom. Also, the object inspection engine is undergoing a major rewrite slated for Chai v5 that should resolve issues with circular references.

**Comment by keithamus** [comment]
Hey @mhchen thanks for the issue.

We've got a bunch of issues all around circular references. We're going to put a lot of attention into this with the work we're doing for chai 5. So I'll close this one, but thanks for filing this issue and please don't hesitate to open any new ones if you find anything new!

**Comment by AdamVig** [comment]
I ran into the same issue with an `HTMLElement` rendered by React. The properties that React adds to elements apparently have circular references.

I noticed it on `strictEqual`, `isNull`, and `isNotNull`. My workaround is to do the comparison myself, which leads to confusing assertion errors:

```TypeScript
assert.isTrue(el === null);
```

@keithamus Since it has been more than a year since you said this would be fixed in Chai 5, would you be willing to take a pull request that fixes it now?
