### ISSUE TITLE
Sort the api documentation navigation.

### ISSUE THREAD

**Issue by ericatbold** [chaijs/chai#1143]
Just what is says.  The left side navigation at http://chaijs.com/api/bdd/ is not alpha sorted.  Kinda annoying.

**Comment by keithamus** [comment]
Hey @ericatbold thanks for this issue!

Thank you for your time in reporting this. I'm going to close this, because we're going to refactor a bunch of stuff including the documentation as part of Chai 5. Rest assured this has been noted, and we'll be making sure to keep this in mind in the future, but nothing is immediately actionable here as we're going to be putting all of our focus into the Chai 5 refactor.
