### ISSUE TITLE
One-liner Statement

### ISSUE THREAD

**Issue by Anthodpnt** [chaijs/chai#1152]
Hi all,

I have a question about how can I test this kind of statement:
```javascript
init() {
  this.onEnter && this.onEnter();
  this.onEnterCompleted && this.onEnterCompleted();
}
```

If I check my Code Climate report the 2 lines in my `init` method are not covered but I can't find a way to cover them. I tried multiple things without success like:

```javascript
it('...', () => {
  // Fake `onEnter` method
  RENDERER.onEnter = () => {};

  // Assertion
  expect(RENDERER.onEnter).to.be.ok;
});
```

Does anyone can help me on this one please ?
Thanks guys!

**Comment by keithamus** [comment]
Hey @Anthodpnt thanks for the issue.

You'd have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

Having said that I would point you in the direction of [chai-spies](https://github.com/chaijs/chai-spies) or sinon, which are both mocking tools that allow you to make fake functions and then assert on them.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.
