### ISSUE TITLE
drop Node.js v4 support

### ISSUE THREAD

**Issue by boneskull** [chaijs/chai#1155]
In a little under two weeks (April 30, 2018), Node.js v4 will be End-of-Life'd.

I wanted to encourage the Chai team to drop support for this version as soon as is feasible. Mocha will also be dropping support ASAP.

Thanks!!

**Comment by keithamus** [comment]
Thanks 👍. We'll drop Node v4 in the next breaking version (Chai @5)

**Comment by keithamus** [comment]
Hey @boneskull. Thank you for your time in reporting this. We will be merging https://github.com/chaijs/guidelines/pull/3 soon, which covers our support cycling - including mentioning that Chai 5 will no longer support Node 4.

I'm going to close this, because there is nothing for us to do right now, but rest assured this has been noted, and we'll be making sure to keep this in mind in the future.
