### ISSUE TITLE
[help] deep equal throws an error but nothing outputed

### ISSUE THREAD

**Issue by dinfer** [chaijs/chai#1164]
As following image shows, the two object may be different, but nothing displayed.

I just want to test whether serialize and deserialize functions works.

```
    const instance = new TextEntity()
    const v = Entity.from(JSON.parse(JSON.stringify(instance)))
    expect(v).to.deep.eq(instance)
```

I also try to output the JSON, by using text diff tool, the JSON is the same.

![image](https://user-images.githubusercontent.com/11496403/41212418-54389c8c-6d70-11e8-8ecc-0e50f04ab8ac.png)

**Comment by lucasfcosta** [comment]
Hi, @dinfer, thanks for you issue 😄

Would you mind taking a look at [this configuration setting](https://github.com/chaijs/chai/blob/058ddadb8422238b418d0c3e8f92e4f757289abd/lib/chai/config.js#L53) and seeing if it solves your problem? This might be due to the size of your object, which is too big and ends up not being displayed in the diff.

For now I'll close this, but please let me know if that didn't solve your problem and we might reopen this issue.
