### ISSUE TITLE
Feature request: wildcard in nested assertion

### ISSUE THREAD

**Issue by Janpot** [chaijs/chai#1167]
I quite often find myself in need to assert for nested properties where the path isn't always fully known. Most of the times when I want to check whether a nested array contains an object with a certain property. Would it be possible to allow wildcards in the path? 
```js
// maybe something like
assert.nestedPropertyVal(obj, 'foo[?].bar', 'baz');
// or
assert.nestedPropertyVal(obj, 'foo[*].bar', 'baz');
// or maybe even with a regex
assert.nestedPropertyVal(obj, 'foo[/.*/].bar', 'baz');
```

**Comment by Janpot** [comment]
> I'd prefer a less ambiguous API

I agree on that point. But it already supports that kind of path notation, so special parsing is already happening.

**Comment by keithamus** [comment]
Hey @Janpot thanks for the issue. Thanks for the extra comments @demurgos.

We'll look into adding this for Chai 5. We've added this to our [Roadmap](https://github.com/chaijs/chai/projects/2) to investigate further. We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.
