### ISSUE TITLE
only depends on assert module

### ISSUE THREAD

**Issue by learnercys** [chaijs/chai#1169]
So, I'm using TDD and I want to use chai assert module, but I don't want to depend on `Expect / Should` API code . Is there a way to avoid this?

**Comment by keithamus** [comment]
Hey @learnercys thanks for the issue.

This is something we're aiming to achieve for Chai 5! This is an implicit part of some new design decisions we have for Chai 5. For now you can follow our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because this is something we have planned.
