### ISSUE TITLE
expect( ).to.be.an('object') failing

### ISSUE THREAD

**Issue by rejas** [chaijs/chai#1174]
Running some tests with chai on Modernizr, but when I run this:

```
      expect(Modernizr.fake).to.be.an('object');
```

I get this exception:

```
addTest Modernizr.addTest supports nested properties:
     AssertionError: expected { detect: true } to be an object
```

But the objects look alright:
 ```
console.log('Modernizr:' + JSON.stringify(Modernizr));
console.log('Modernizr.fake typeof: ' + typeof Modernizr.fake);
```
results in:
```
Modernizr:{"_q":[null],"_config":{},"fake":true}
Modernizr.fake typeof: object
```

What do I make wrong? node is v8.11.2 chai the latest 4.1.2

**Comment by keithamus** [comment]
Hey @rejas thanks for the issue.

I'm not sure this is a bug with Chai, but sadly I cannot reproduce your code example. If you could set up a reduced test case, perhaps a repository with dependencies installed and the failing test to see - then I could take a look at why this is failing.

Having said that - you'd likely have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because I believe its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.
