### ISSUE TITLE
Advice to a sibling repository: how do you manage this repo?

### ISSUE THREAD

**Issue by i0natan** [chaijs/chai#1184]
Hey,

Looking for a friendly advice: [our repo here](https://github.com/i0natan/nodebestpractices) just grew a little bit and we look for tools/tips about how to manage many PRs, permissions, and sub-repos. Do you use any other tool that GitHub for management? what type of GH account do you use (considering that developer account has limited permissions settings and team account has significant costs)?

Thanks!

Best,
Yoni

**Comment by keithamus** [comment]
Hey @i0natan thanks for the issue.

We don't get so many PRs, so might be the wrong place to ask. You could use automation such as https://github.com/probot/probot which will let you automatically label, comment or close PRs.

We just use the free GitHub account. There's no limitation between free and paid in terms of permissions - the only thing paid account gives you is private repository access. 

I'll close this issue because this isn't a bug within chai. Thanks for reaching out though! If you have any more questions feel free to ask in this thread 😃
