### ISSUE TITLE
How to keep soft assertions?

### ISSUE THREAD

**Issue by bharathmadishetti** [chaijs/chai#1202]
Hi,

I am using Mocha/Chai combination to write scripts. 

How can I keep multiple assertions in a single 'it' block so that failing of one assertion should not stop validating of remaining assertions?

In below code example, 2nd and 3rd assertions are not getting executed because first assertion is throwing an error. I want all assertions to be validated irrespective of whether an assertion is passed/failed. Basically I am looking for soft assertion where it should report the error but should not stop the test executing further. Could you please check and help how to keep soft assertions? Please do not suggest that I should use one 'it' block for each assertion.

it("Loop", function(){
        chai.assert.equal(2,3,"Verify both are equal"); 
        chai.assert.equal(2,4,"Verify both are equal"); 
        chai.assert.equal(2,2,"Verify both are equal"); 
    });

**Comment by keithamus** [comment]
Hey @bharathmadishetti thanks for this issue!

The way Chai works is that we don't have a notion of "soft assertions". The assertion should either prove or disprove a thing, and that should fail the entire test (because whatever the description of "it" is, no longer holds true). I'm not suggesting you only use one assertion per it-block, but perhaps you could rewrite the it-block in a way where it holds for the assertions inside of it? It's difficult to give an example of what I mean from your code example, but if you provide a more concrete example I'm sure I could help with that.

Thank you for your time in reporting this. I'm going to close this, because there is nothing for us to do right now, but rest assured this has been noted, and we'll be making sure to keep this in mind in the future.

**Comment by raosaqib** [comment]
If I have multiple steps in  a single it block & my assertion fails ..but i need to go to the next step. but as soon as expect fails it doesn't go to the next step.

**Comment by junaid1840** [comment]
Having same problem. 
```
it('Should check status code of all external links',async () => {
        const allExternalURLsReport: any = await kayakAirlineFees.getReportOfAllURLs();
        allExternalURLsReport.forEach((currentSite: any) => {
            console.log(currentSite);
            it('Junaid',() => {
                expect(currentSite.statusCode).to.equal(200);
            })
        });
    })
```
The loop breaks when any assertion is failed. e.g if loop has 10 iterations and the 2nd one failed then it stops iteration after the 2nd one.
Please Help.

**Comment by raosaqib** [comment]
@junaid1840  you need to override the chai assertion  and need to create a wrapper around the assertion you are using and handle it using try/catch

**Comment by alfonso-presa** [comment]
I was looking for this functionality and as chai didn't offer it, I created a wrapper as commented by @raosaqib. You could give it a try if you need soft assertions: https://github.com/alfonso-presa/soft-assert
