### ISSUE TITLE
Warn when chaining negation expression

### ISSUE THREAD

**Issue by c-bandy** [chaijs/chai#1210]
This issue extends the concerns of #261:

>When chaining a negation statement (`.not`) followed by several assertions, it applies to all these assertions. When read as a sentence, it does not make sense.

```js
expect(true).to.not.be.undefined.and.to.be.true; // AssertionError: expected true to be false
```

The resolution was to split up your chain into multiple expect statements, which seems fine - but this unexpected behavior should be communicated to the user more clearly.

~It should be pretty easy to implement -~ if a negation is followed by two or more assertions, print a warning in the output. This lets the user know that they probably want to break up their expect statements.

**Comment by meeber** [comment]
Currently assertions don't have knowledge of how many assertions preceded it in the chain. My first impression is that it'll be tricky to implement. Requirements would probably need to be:

1. The functionality exists at a low enough layer such that existing assertions (both builtin and 3rd party plugins) would automatically inherit the functionality without having to be individually updated.
2. The change correctly handles every situation in which one assertion calls multiple other assertions under the hood.

Although not as effective, an update to the docs would be a lower cost alternative.

Also pinging @keithamus. He might have insight into whether or not this problem carries over (and is more easily handled) in the Chai v5 rewrite.

**Comment by keithamus** [comment]
Hey @c-bandy thanks for the issue.

As @meeber alludes to - this problem won't be carried over in the chai 5 rewrite. Instead, `and` does _not_ carry over any of the keywords associated with the previous assertion (because we have had many issues about how unintuitive this is). Additionally, every assertion will have the full knowledge of the whole expression chain and so we can (and in fact Chai 5 already does) emit warnings about badly formed chains.

I'll close this because I think we've got this covered nicely in Chai 5. As always you can track the progess of Chai 5 in the Roadmap https://github.com/chaijs/chai/projects/2!
