### ISSUE TITLE
`expect.to.throw` implementation details

### ISSUE THREAD

**Issue by ansermino** [chaijs/chai#1221]
I'm somewhat confused by the implementation of `expect.to.throw`. I'm opening this out of curiosity so please bare with :smile_cat: 

One of the examples in the docs is as follows:
```
var err = new TypeError('Illegal salmon!');
var badFn = function () { throw err; };

expect(badFn).to.throw(err);
```

In what case is this useful? When can we ever expect to instantiate and pass in the error instance that is thrown inside a function? 

I was ultimately looking to assert the parameters of custom error messages. For example, an error detailing `got: x, expected: y`. Perhaps this is naive but I was expecting to be able to instantiate an error of the same type and with the same parameters and use it as the expected result. 
```
const a = new CustomError(1, 2)
const throwFn = () => {
    throw new CustomError(1, 2)
}
...
it('should produce a CustomError', (done) => {
    expect(throwFn).to.throw(a)
})
```
Seemingly the inclusions of the stack trace in the equality comparison causes this to fail. There are work arounds for this, such as:
```
const a = new CustomError(1, 2)
const throwFn = () => {
    throw new CustomError()
}
...
it('should produce a CustomError', (done) => {
    try {
        throwFn()
    } catch (e) {
        assert(e.message === a.message, 'Thrown error does not match new instance of error')
        done()
    }
    expect.fail()
})
```
But the question remains, would you really ever be able to expect to pass in the instance of the error thrown? The example in the docs just seems to be somewhat misleading with no practical uses. Would love to know if I'm missing something here, or if there is a cleaner way to achieve my goal.

**Comment by ansermino** [comment]
Looks like #1220 includes the removal/change of this behavior :smile: Still interested in whether there is a better way to achieve this soft-equality, perhaps I can be an advocate for natively supporting this sort of comparision....

**Comment by meeber** [comment]
@ansermino Right, it's my opinion that the behavior described [here](https://github.com/chaijs/chai/blob/929c109e1ab20a3de89ff0e1045f77d9f84e9987/lib/chai/core/assertions.js#L2468-L2475) is seldom used, and that most users would benefit from having a deep equality check be performed instead, which as you noted is one of the changes I'm aiming for in #1220. I can't speculate on the motivation for the current behavior. It was present even in [Chai v1 in 2012](https://github.com/chaijs/chai/blob/ec07b48ed0c594122a9754de7aae4e25d6872de2/lib/assertion.js#L922), and the original implementer is no longer active. `.throw` has historically been our most troublesome assertion for a number of reasons, and although it has gone through several iterations over the years to fix various problems, it still isn't where it needs to be.

Somewhat related: Chai's deep equality algorithm also falls back to strict (`===`) equality for `Error` instances, so code like `expect(err1).to.deep.equal(err2)` suffers from the same problem. However, the next major release of Chai will treat `Error` instances differently during deep equality comparison as a result of [these changes](https://github.com/chaijs/deep-eql/releases/tag/v4.0.0) in the underlying deep equality library. You can follow the various links for issues and PRs in that release page for details about the upcoming algorithm, and the challenges that led to that algorithm being chosen. The upcoming algorithm ends up being similar to what's done by lodash as well as Node's builtin assertion library. Essentially, it only compares the `name`, `message`, and `code` properties, rather than a full deep equality comparison.

One workaround that exists now is assertion chaining:
```js
const { expect } = require("chai");

describe("tests", function () {
  it("test", function () {
    const myErr = TypeError('waffles');
    myErr.customProp1 = 123;
    myErr.customProp2 = 456;

    const badFn = function () { throw myErr; };

    // One custom property
    expect(badFn).to.throw(TypeError, 'waffles')
      .with.property('customProp1', 123);

    // Multiple custom properties
    expect(badFn).to.throw(TypeError, 'waffles').that.includes({
      customProp1: 123,
      customProp2: 456,
    });
  });
});
```

**Comment by ansermino** [comment]
Thanks for the detailed response @meeber! Will stay tuned for the upcoming changes :+1:
