### ISSUE TITLE
calling a double arrow function not acting as expected

### ISSUE THREAD

**Issue by aiyk** [chaijs/chai#1222]
I have this function in my vue store module which takes in state and criteria arguments and returns a value based on the feed in arguments
```
filteredCollections: state => criteria => {
   ...
}
```

in my test file, i have referenced this function and passed its return value to a constant as shown below

`const result = filteredCollections(state, criteria);`

instead of getting back the return value of my function in the result constant, i get back the function itself in my constant. this goes to say that chai is finding it difficult running functions defined this way.

is there a work around for this?

I'm really sorry if I did a poor job submitting this issue, bare with me guys, its my first.

thanks a bunch

![image](https://user-images.githubusercontent.com/39383181/50768177-d24e3c80-127f-11e9-9225-fa2d140bece6.png)

**Comment by keithamus** [comment]
Hey @aiyk thanks for the issue!

The issue here is that the arrow function style you're using (which to give it a term would be something like "currying of unary functions") does not facilitate calling with multiple arguments, like you do with `const result`.

See the following:
```js
const filteredCollections = state => criteria => 1

typeof filteredCollections(state, criteria) === 'function'

typeof filteredCollections(state)(criteria) === 'number'
```

Calling `filteredCollections` one returns a function, which takes one argument. Calling it twice returns the return value of the second function. If you want to call it with multiple arguments you'll need to change the function signature:

```js
// Alternative

const filteredCollections = (state, criteria) => 1

typeof filteredCollections(state, criteria) === 'number'

typeof filteredCollections(state) === 'number'

typeof filteredCollections(state)(criteria) // TypeError: 1 is not a function
```

Thank you for your time in reporting this. I'm going to close this, because there is nothing for us to do - it's not an issue with Chai. Feel free to continue commenting here and if you do find a bug please don't hesitate to file it!

**Comment by aiyk** [comment]
thanks so much @keithamus , this was quite insightful. all i needed do was to call the currying function like so `const result = filteredCollections(state)(criteria)` and me test started passing. thanks again

**Comment by keithamus** [comment]
Any time @aiyk! Happy coding 😄
