### ISSUE TITLE
How to check type of the array in Chai 

### ISSUE THREAD

**Issue by pbelamkar** [chaijs/chai#1226]
E.g. Json : {
    "statusCode": "SCS",
    "statusMessage": "Success",
    "reply": [
        {
            "indexId": 657,
            "sectionData": "Text",
            "isHide": true,
            "defaultData": "Not Item"
        },
              ]
}

I want to validate type of the "reply", now type of the reply is array. So how to assert in Chai. 
I am using this "response.reply.should.be.type('Array');" But getting this error. 
**to have type Array expected 'object' to be 'Array'.** 
And if i am using this response.reply.should.be.type('object') then it's working. 

So my question is which is correct or we have other way to validate type of the array.

**Comment by pbelamkar** [comment]
I am getting following this error when i used as  response.reply.should.be.an('array'); 
Uncaught TypeError: response.body.reply.should.be.an is not a function

**Comment by meeber** [comment]
The code I pasted above works for me in an empty project. Can you create a reproducible example and link to it on GitHub so I can run the code on my system and get the same error?

**Comment by pbelamkar** [comment]
If you use this code then getting same error. 

let chai = require('chai');
const should = require('should');
let fs = require('fs');
rejectUnauthorized: false;
strictSSL: false;
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
let chaiHttp = require('chai-http');
let request = require('request');

describe("tests", function () {
  it("test1", function () {
    const response = {
      "statusCode": "SCS",
      "statusMessage": "Success",
      "reply": [
        {
          "indexId": 657,
          "sectionData": "Text",
          "isHide": true,
          "defaultData": "Not Item"
        },
      ]
    };

    response.reply.should.be.an('array');
  });
});

**Comment by meeber** [comment]
The problem is that when you run `const should = require('should')`, you're actually importing a completely different non-Chai assertion library called [Should.js](https://shouldjs.github.io/) (which does have a `.type` assertion instead of `.an`). You should use either Chai.js or Should.js, not mix them together. If you decide to use Chai.js, then see [this page](https://www.chaijs.com/guide/styles/) for guidance on importing Chai's `should` interface. If you decide to use Should.js, then you'll need to reach out to their team for troubleshooting help; it's a completely different project run by completely different people.

**Comment by pbelamkar** [comment]
Yes i want to use Should.js could you please help me how to contact their team. 

Thanks.

**Comment by meeber** [comment]
https://github.com/tj/should.js/
