### ISSUE TITLE
 Cannot do `deep.nested` on an array, have to wrap it with an object

### ISSUE THREAD

**Issue by Noitidart** [chaijs/chai#1235]
This was a stackoverflow question - https://stackoverflow.com/q/53906051/1828637

He has a `const payload = [{ id: 0 },{ id: 1 }]` and wants to do the following:

    expect(payload).to.nested.include({
      '[0].id': 0,
      '[1].id': 1
    });

But it does not work. He has to wrap it to get this to work:

    const wrappedPayload = { a: payload };
    expect(wrappedPayload).to.nested.include({
      'a[0].id': 0,
      'a[1].id': 1
    });

I think this is a bug.

**Comment by meeber** [comment]
@Noitidart The `.include` assertion is a bit frustrating because its behavior changes based on the target's type.

[In the case of an array](https://github.com/chaijs/chai/blob/1cededa167ebf1f433d82813abd6db4d774aff71/lib/chai/core/assertions.js#L324-L327) (as in your first example), `.include` is simply checking if the supplied value (`{ '[0].id': 0, '[1].id': 1}`) is a member of the target array, which it's not. The `nested` flag doesn't even come into play in this case because there are no property-by-property checks being performed.

[In the case of an object](https://github.com/chaijs/chai/blob/1cededa167ebf1f433d82813abd6db4d774aff71/lib/chai/core/assertions.js#L329-L332) (as in your second example), `.include` is checking that each property in the supplied value is also a property in the target object. This property-by-property check is affected by the `nested` flag.

For this specific example, I'd recommend the `.members` assertion instead:

```js
const payload = [{ id: 0 },{ id: 1 }];        
                               
expect(payload).to.include.deep.members([                                    
  { id: 0 },                                                                 
  { id: 2 },                                                                 
]);  
```

**Comment by Noitidart** [comment]
Thanks @meeber for that indepth reply. With members though I can't ensure order when skipping certain entries though can I? 

Like if I had:
```
const payload = [{ id: 0 },{ id: 1 }, {id: 2}];        
                               
expect(payload).to.include.deep.members([                                    
  { id: 0 },                                                                 
  i_dont_want_to_check_2nd_el,      
  { id: 2 },                                                                 
]);
```

**Comment by Noitidart** [comment]
I refine the example the here to show what I'm trying to do:

This was a stackoverflow question - https://stackoverflow.com/q/53906051/1828637

He has a `const payload = [{ id: 0, value: 'foo' }, { id: 1, value: 'bar' }, { id: 2, value: 'qux' }]` and wants to do the following:

    expect(payload).to.nested.include({
      '[0].id': 0,
      '[2].value': 'qux'
    });

But it does not work. He has to wrap it to get this to work:

    const wrappedPayload = { a: payload };
    expect(wrappedPayload).to.nested.include({
      'a[0].id': 0,
      'a[2].value': 'qux'
    });

**Comment by meeber** [comment]
In terms of current functionality, I don't think there's a silver bullet. Some options:

```js
// Option 1
const wrappedPayload = { a: payload };
expect(wrappedPayload).to.nested.include({
  'a[0].id': 0,
  'a[2].value': 'qux'
});

// Option 2
expect(payload).to.have.nested.property('[0].id', 0);
expect(payload).to.have.nested.property('[2].value', 'qux');

// Option 3
expect(payload).to.include.deep.ordered.members([
  { id: 0, value: 'foo' },
  { id: 1, value: 'bar' },
  { id: 2, value: 'qux' }
]);
```

In terms of possible changes to functionality to support this:

1. Update the `.include` assertion to support `.nested` with array targets
2. Update the `.members` assertion to support `.nested`

**Comment by Noitidart** [comment]
Thanks very very much for sharing this info @meeber !
