### ISSUE TITLE
Promise based assertions without a plugin

### ISSUE THREAD

**Issue by JustinBeckwith** [chaijs/chai#1246]
Greetings folks!  We've started to pick up chai in a many of our npm modules, and so far we're loving it.  Coming from [assert](https://nodejs.org/api/assert.html) in node core, one of the assertions I find myself really missing is `assert.rejects`.   I'd love to see this added (and I'm happy to submit a PR) for a few reasons:

- Parity with the `assert` module in nodejs core 
- `async/await` is about to land, and promises are far more at the center of our workflows than they used to be

I know that [chai-as-promised](https://github.com/domenic/chai-as-promised) includes an assertion that will do this for me, but I would prefer not to deal with an additional module for what feels like a feature that could live in core.

Thoughts appreciated!

**Comment by keithamus** [comment]
Hey @JustinBeckwith thanks for the issue!

We have this planned for Chai 5. The current architecture in Chai 5 is that every error object is a "thennable" (it has a `then` method) and calling it will turn the assertion into a Promise. In addition we'll have some assertions for Promises such as `rejects` and `fulfills`. I've added a card to our Roadmap https://github.com/chaijs/chai/projects/2 for tracking. We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.

**Comment by nwalters512** [comment]
👋 I don't see this mentioned in the v5 changelog and can't seem to find this functionality in the API. Did this end up being implemented?
