### ISSUE TITLE
eql / deep.equal returns unhelpful output

### ISSUE THREAD

**Issue by klemens-u** [chaijs/chai#1247]
I'm using chai with postman.
I compare two objects with the eql / deep.equal assertion, and they are not equal.
At the momen the return is something like:
`AssertionError: expected { Object (...) } to deeply equal { Object (...) }`

This return is not helpful at all, as there is no reporting on the differences.
I would expect something like this:

`AssertionError: expected { Object (...) } to deeply equal { Object (...) }` + diff like output of (for example) the stringified json representation.

That would make debugging so much easier!

**Comment by keithamus** [comment]
Hey @klemens-u thanks for the issue.

At the moment we rely on your test runner to provide information like diff output. This is something we plan to change in great detail with Chai 5. We've got tasks to improve `loupe` - our inspection engine - on our Roadmap https://github.com/chaijs/chai/projects/2! We'll be releasing chai 5 soon, but for now I'll close this issue because it is tracked on our roadmap.

**Comment by jawn** [comment]
Hi @keithamus, any news on this chai 5 version?

**Comment by keithamus** [comment]
Hi @jawn we're working on loupe, the inspection engine. We may have a release soon, at which point we will look at if it is possible to release a `4.x` release which will fix this issue, instead of waiting for chai 5.

**Comment by klemens-u** [comment]
Any update on this?
