### ISSUE TITLE
`undefined` should be NaN

### ISSUE THREAD

**Issue by ps2goat** [chaijs/chai#1255]
I'm currently using version 4.2.0 of chai.

I found the following discrepancy.  The first test works, while the second does not.  I would expect the second to work and is less verbose.  It's not a big deal for me, but it certainly doesn't follow actual js expectations (though js doesn't fit my expectations in this case).

tests:
```
// works
it('undefined is NaN', async () => {
    assert.isTrue(isNaN(undefined));
});

// does not work. error: expected undefined to be NaN
it('undefined is NaN', async () => {
    assert.isNaN(undefined);
});
```

Actual js in a console, and the reason for trying this test: 
![image](https://user-images.githubusercontent.com/5384732/58124458-de55ed80-7bd3-11e9-8ea8-586cd71fae68.png)

**Comment by keithamus** [comment]
Thanks for the issue @ps2goat!

Chai uses [`Number.isNaN` under the hood](https://github.com/chaijs/chai/blob/master/lib/chai/utils/isNaN.js), which believe it or not behaves differently to the global `isNaN`. `Number.isNaN` returns `false` for `undefined` while `isNaN` returns `true`:

```js
assert(Number.isNaN(undefined) === false)
assert(isNaN(undefined) === true)
```

`isNaN` was kind of always broken, and `Number.isNaN` was added in ES2015 to address these issues. Or as [mdn puts it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN):

> Note: coercion inside the isNaN function has [interesting](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN#Confusing_special-case_behavior) rules; you may alternatively want to use [Number.isNaN()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN), as defined in ECMAScript 2015.

I'll close this issue; because I don't think there is anything here for us to fix. If you think there is, please don't hesitate to reply and I'll re-open the issue for further discussion.
