### ISSUE TITLE
should.have.property does not diff objects?

### ISSUE THREAD

**Issue by josh-byster** [chaijs/chai#1258]
Hi, I'm using supertest + mocha + chai to test an Express app, and I wrote a simple function wrapper that I use to assert that my response object has a property:

```js
var chaiAssertProperty = (res,property,expected) => {
  expect(res.body).to.have.nested.property(property,expected)
}
```

One of my calls with the supertest chain is:
```js
.expect(res => chaiAssertProperty(res, "rqst.params",{"pt":60,"stop_id":"IU"}))
```

Here's what I get:
```js
AssertionError: expected { Object (time, new_changeset, ...) } to have nested property 'rqst.params' of { pt: 60, stop_id: 'IU' }, but got { pt: 60, stop_id: 'IU' }
      + expected - actual



      at chaiAssertProperty (tests/server.test.js:7:35)
      at request.get.expect.expect.expect.expect.res (tests/server.test.js:45:22)
      at Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
      at Test.assert (node_modules/supertest/lib/test.js:173:18)
      at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1609:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```
All other usage works as-expected with the method `chaiAssertProperty` — I just run into trouble with the object. 

As seen above, the objects do not differ, but Chai is saying that they are. If I change the pt value in my expectation to 70, for example, then Chai will show the diff and will be correct that the two objects differ. I'm curious if this is a Chai bug or (more likely) I'm misunderstanding the API usage. Thank you!

**Comment by lucasfcosta** [comment]
Hi @josh-byster,

When using `nested` you need to add the `deep` flag in order to get a [`nonStrict`](https://github.com/chaijs/deep-eql) comparison. Since you're comparing `objects` they will be different instances and therefore fail when doing a `strict` comparison.

You can see this if you do:

```js
// Should fail because `second` is an object and therefore will be a different instance in `a` and `b`.
const a = { first: { second: { third: "example" } } };
const b = { first: { second: { third: "example" } } };
expect(a).to.have.nested.property("first.second", b.first.second);
```

And then try:

```js
// Should pass since we do a `deep` comparison
const a = { first: { second: { third: "example" } } };
const b = { first: { second: { third: "example" } } };
expect(a).to.have.deep.nested.property("first.second", b.first.second);
```

If you want to add docs for this use-case I think it would be an awesome PR, but for now I'm then closing this issue.

In case you think I have misunderstood your problem or answered incorrectly feel free to let us know and we will reopen this.
