### ISSUE TITLE
Add application-level express middleware in test

### ISSUE THREAD

**Issue by ravecat** [chaijs/chai#1283]
Demo: https://codesandbox.io/s/mocha-chai-http-tests-o31ov
I try to add application-level middleware in testing stage like this

```
it("GET/ Get custom response", function(done) {
    app.use("/custom", (req, res, next) => {
      res.status(200).send({
        customMessage: "custom",
        customData: {
          version: "v1"
        }
      });
    });

    chai
      .request(app)
      .get("/custom")
      .end((err, res) => {
        console.log("CUSTOM", res.body);
        res.should.have.status(200);
        res.body.should.be.a("object");
        res.body.should.have.property("customMessage");
        res.body.should.have.property("customData");
        done();
      });
  });
```

But test doesn't use that, it falls to 404-middleware in root. How can I use custom route in test?

**Comment by keithamus** [comment]
Hey @ravecat thanks for the issue.

You'd have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.
