### ISSUE TITLE
Roadmap Chai 5 / Es module version?

### ISSUE THREAD

**Issue by daKmoR** [chaijs/chai#1284]
It has been quite a while since the last release/communication 😬 

A lot has happened since then - es modules in particular and it seems finally the whole javascript "world" converges to a single way of loading other javascript code.

It seems es modules will be considered in chai 5? https://github.com/chaijs/chai/issues/1232#issuecomment-460055944

So the question is - is there any rough roadmap or plan for it?
which may include (just some random suggestions from the top of my head)
- use es modules and distribute as es module (+es 5 dist)
- incorporate es modules in plugin loading system
- provide typescript types
- setup all packages with a lerna monorepo (using yarn workspaces)
- ...

**Comment by keithamus** [comment]
Hey @daKmoR thanks for the issue!

As explained in #1232 we will be moving to ES modules in chai 5. We have a private repo which sketches out a version of Chai 5 which includes ES modules, a new plugin system, and uses Lerna. We're in the process of turning that sketch into a reality, with the first step of converting [this repo into a lerna repo](https://github.com/chaijs/chai/pull/1249).

We'll make a 4.3.0 release of chai (https://github.com/chaijs/chai/pull/1266), then likely start converting the repo to Lerna and bringing in some of the concepts from the private repo. Things are slow moving because many of the core Chai maintainers are on vacation or moving or have other high priority things going on in their life.

The roadmap we have is at https://github.com/chaijs/chai/projects/2, which describes some of the new ideas we have but it doesn't cover things we already have in our Chai 5 design sketch. Again, we'll be moving those ideas to this repo soon but it will take time. I don't want to say how long it will be as things can and likely will change.

I'll close this issue, as there's nothing _actionable_ from this issue that we need to fix or resolve with Chai. Please feel free to keep the conversation going though, I'm happy to continue commenting on this issue and if you have any other bugs or feature requests with Chai please don't hesitate to raise new issues 😄

**Comment by daKmoR** [comment]
hey @keithamus 🤗 

I'm still quite interested in this 🤗 so if there is any new information - I would be thrilled to hear it 🤗

**Comment by daKmoR** [comment]
it is a new year 🤗 any new(year)s? 😬 🤣

**Comment by keithamus** [comment]
Sadly no. We're making slow progress, due to personal circumstances. https://github.com/chaijs/loupe needs updating with more tests and to pass the build, then we can cut a 2.0 release and hopefully bring it into Chai 4, which will help us reduce the amount of code we need to transition out in Chai 5.
