### ISSUE TITLE
Release plan?

### ISSUE THREAD

**Issue by rhenwood-arm** [chaijs/chai#1288]
Hi @keithamus,

I would like to pick up the PhantomJS removal patch: https://github.com/chaijs/chai/pull/1204 
Can you make a release to simplify this for me?

**Comment by keithamus** [comment]
Hi @rhenwood-arm thanks for the issue, but I'm not sure I understand what you're asking here.

PhantomJS is a devdependency, so should have no affect when you install chai.

We have a release due very shortly - the PR is here: https://github.com/chaijs/chai/pull/1266.

I'll close this issue because I don't think there is anything to action here. If you see any more issues please let us know!
