### ISSUE TITLE
Integrating chai-http and chai-enzyme question (with solution)

### ISSUE THREAD

**Issue by perrin4869** [chaijs/chai#1291]
Yesterday I ran into https://github.com/chaijs/chai-http/issues/150, and after tracking down the root cause, I found that both plugins register an `html` and `text` property. The following will crash:

```javascript
const chai = require('chai');
chai.use(require('chai-http'));
chai.use(require('chai-enzyme')()); // TypeError: Cannot read property 'headers' of undefined
```

The reason for this, is that `chai-enzyme` will try to call `overwriteMethod` on `Assertion.prototype.html`, which is defined as a `getter` by `utils.addProperty` in `chai-http`.

A workaround I have found, is to do the following:

```javascript
const chai = require('chai');

const propertyToMethod = (name) => (chai, utils) => {
  const { Assertion } = chai;
  const { get } = Object.getOwnPropertyDescriptor(Assertion.prototype, name);
  delete Assertion.prototype[name];
  utils.addMethod(Assertion.prototype, name, get);
};

chai.use(require('chai-http'));

chai.use(propertyToMethod('html'));
chai.use(propertyToMethod('text'));

chai.use(require('chai-enzyme')());
```
Before `chai-enzyme` runs, we convert `html` and `text` into methods, and let `chai-enzyme` overwrite those instead.
Of course, this is much less than ideal, so I thought I would make an issue here to ask if there is a preferred workaround, or if `chai@5` will tackle these kind of plugin collisions, etc.
Thanks!

**Comment by keithamus** [comment]
Hey @perrin4869 thanks for the issue and the detailed description and solution!

As you suggested, Chai 5 has been re-architected to work around these exact kind of issues. Plugins declare their assertions and Chai does all the wiring itself, avoiding collisions and the like.

I'll close this because - while it does suck that it'll remain broken in Chai 4 - Chai 5 will fix this and there's nothing for us to action with this issue. If you have any other issues please don't hesitate to raise them!
