### ISSUE TITLE
undefined 'global' in browser script

### ISSUE THREAD

**Issue by smichea** [chaijs/chai#1297]
When trying to load  https://www.chaijs.com/chai.js  in nashorn js engine i get :
javax.script.ScriptException: ReferenceError: "global" is not defined in https://www.chaijs.com/chai.js at line number 10478.

`var globalObject = typeof self === 'object' ? self : global;`

**Comment by keithamus** [comment]
Hey @smichea thanks for the issue!

Chai does not currently support Nashorn, we only claim to support web browsers and Node.js. It looks as though OpenJDK also no longer supports Nashorn (I'm looking at [`JEP 335`](http://openjdk.java.net/jeps/335)). 

I'm going to close this issue for now - just because I can't see us being able to add support for a now deprecated project, but if you can provide more information to the contrary I'd be happy to look into this further.
