### ISSUE TITLE
expect().to.deep.equal fails to handle arrays vs undefined

### ISSUE THREAD

**Issue by ThisIsMissEm** [chaijs/chai#1356]
Given the code:

```
expect({
  scopes: []
}).to.deep.equal({
  scopes: undefined
})
```

The result is a failure and the output is:

```
  -  "scopes": []
  +  "scopes": [undefined]
```

Whilst the failure is correct, the output should be:

```
  -  "scopes": []
  +  "scopes": undefined
```

This behaviour had me very confused as I was doing an array concatenation on the code that generated the value for the scopes property of the expecting object, and I thought I'd done something wrong and somehow concatenated undefined into the `scopes` array, but it's actually just that the `scopes` property should've been `undefined` not an array per my assertion expected value.

**Comment by keithamus** [comment]
Hey @ThisIsMissEm thanks for the issue!

The `-`/`+` prefixes lead me to believe you're looking at the output from a test failure using Mocha, is this the case?

Chai doesn't actually do the diffing, it raises an `AssertionError` with `expected` and `actual` properties. Test runners like `mocha` are then supposed to output a diff based on those properties.

In the next release of Chai we're going to tackle this a bit better by putting more valuable information in the error message, instead of relying on test runners to diff `actual`/`expected`. However test runners will still output diffs like this.

I'm going to close this issue as there's nothing actionable here for the Chai project. You could perhaps raise this issue on the issue tracker for your test runner, e.g. https://github.com/mochajs/mocha/issues/new

**Comment by ThisIsMissEm** [comment]
Okay, yeah, looks like it was an issue in mocha... apparently when it transforms the `actual` and `expected` properties into the diff, it uses a stringify method which results in `undefined` being printed as `[undefined]` — https://github.com/mochajs/mocha/blob/ad03d2972deba18a7a214324fbd73cb14bbe0d79/lib/utils.js#L241
