### ISSUE TITLE
Don't stop test on AssertionError

### ISSUE THREAD

**Issue by tripuzv** [chaijs/chai#1474]
How to make sure that the test does not stop in case of AssertionError(expect method).
WDIO, Mocha, Chaijs as assetion library

**Comment by UlrichEckhardt** [comment]
`assert()` and its companions throw an exception on failure, which is why further tests are skipped. I find that reasonable, because it allows you to base one step of evaluating the results on a previous one. For example, first check that `response != null`, then check that `response.status == 200`.

If two assertions are independent, put them into separate `it(...)` calls. If an assertion in one fails, the other one is still called.

**Comment by koddsson** [comment]
What @UlrichEckhardt said. I'm gonna close this as working as expected.
