### ISSUE TITLE
TypeError: Unknown file extension ".ts" with Chai 5.0.0 and later

### ISSUE THREAD

**Issue by npapagna** [chaijs/chai#1607]
I get `TypeError: Unknown file extension ".ts"` when trying to run `mocha` tests using `ts-node` with `chai 5.0.0` and later.
Downgrading it to `4.4.1` seems to fix the issue.

Check this repo [with a minimal example that reproduces the bug](https://github.com/npapagna/chai-unknown-file-extension-ts-repro)

**Comment by 43081j** [comment]
this is because chai 5.x is esm-only

if you're in a commonjs project, you should stick to 4.x (which we are still supporting) or migrate to ESM (add `type: "module"` to your `package.json`).

you can see an example of an esm project working with ts-node and mocha here:
https://gist.github.com/43081j/78ce1392abb5043b02a29355006880a5/

**Comment by npapagna** [comment]
Thanks, that worked great!
