### ISSUE TITLE
to.match acts weird

### ISSUE THREAD

**Issue by Kenzku** [chaijs/chai#162]
Have no idea why: 

``` javascript
1 var base64 = 'VQ/W4MfP8UGFohi29utgCkr+jQI=';
2 var regex = /^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)$/gim;
3 chai.expect(base64).to.match(regex)
```

It says:
`expected 'VQ/W4MfP8UGFohi29utgCkr+jQI=' to match /^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)$/gim`

but it works, if `base64.match(regex)[0]` (other chai.expect.to.match works perfect, and I have no idea why here is an exception)

moreover, the `regex` is valid and can match the `base64` by `http://gskinner.com/RegExr/`

**Comment by ryanemax** [comment]
how to do a quick test? I got the same Issue

not work with:
``` js
let message = "dB7FWJ0_pu2wcin5RcXX7CuDg7mZ7OsKb4V7ZrX1:-Aa0UiEV2wPBP0eSMFZyXFMS_0Q=:eyJzY29wZSI6ImFuYXMtY2xvdWQiLCJkZWFkbGluZSI6MTQ3NzU3Nzk0Nn0="

expect(message).to.match(/.*:.*:.*=$/)
```
there is no any respone when match, but only it not match will throw an error.

**Comment by vieiralucas** [comment]
Hello @ryanemax 

I'm not sure If I understand your problem, since you are expecting the message to match the regex, chai will only throw if the message don't match the regex. If you want to assert that the message do not match the regex you can write this assertion:
```js
expect(message).to.not.match(/.*:.*:.*=$/)
```

If you wanna play with chai, you can use this jsfiddle
