### ISSUE TITLE
chai for browser is still 4.3.8?

### ISSUE THREAD

**Issue by danny0838** [chaijs/chai#1648]
The hotlinking file on the website https://www.chaijs.com/chai.js has `exports.version = '4.3.8';`, while the latest releases in this repo are `4.5.0` and `5.1.1`.

Additionally there is also `Copyright(c) 2011-2014 ...`, which seems very old.

I'd like to know why the browser version is outdated? Or is there some packaging issue resulting an incorrect version information?

**Comment by koddsson** [comment]
Looks like it's broken and I'm not sure if we'll put in the work to fix it. Probably best to use a 3rd party CDN like [jsDelivr](https://www.jsdelivr.com/?docs=esm) or [unpkg](https://www.unpkg.com/) instead.

https://www.unpkg.com/chai@5.1.1/chai.js
https://cdn.jsdelivr.net/npm/chai@5.1.1/+esm

**Comment by danny0838** [comment]
I'm specifically talking about chai.js in browser. The file is provided in your official site, if it's broken should you either fix it or provide a working alternative to it (both links provided in your comment above do NOT work in the browser).

**Comment by koddsson** [comment]
> Both links provided in your comment above do NOT work in a non-esm context in the browser

What's non-esm context? I got it working here: https://codepen.io/koddsson-the-decoder/pen/xxvgZab but I guess that's "esm context"? Do you have a reproduction for your issue?

> The file is provided in your official site, if it's broken shouldn't you either fix it or provide a working alternative to it?

I just don't think it will get fixed with the number of contributions to chai right now. We welcome any pull request that fixes the issue.

**Comment by danny0838** [comment]
Non-esm context is a context without ES6 module, which is mostly browser global or AMD (require.js).

The previous chai.js in the official site supported them with a UMD-like style.

**Comment by koddsson** [comment]
> Non-esm context is a context without ES6 module, which is mostly browser global or AMD (require.js).

[JavaScript modules are available in all browsers and runtimes I can think of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#browser_compatibility) so that shouldn't be a problem.

If you prefer not to use JavaScript modules for whatever reason you can use `chai@4` still. I made a PR to the mocha docs to showcase how this is done it you'd like to check that out: https://github.com/mochajs/mocha/pull/5230

**Comment by danny0838** [comment]
Thanks. Just to make sure: is there any timeline that support of v4 will end?

**Comment by koddsson** [comment]
> Thanks. Just to make sure: is there any timeline that support of v4 will end?

None right now. We encourage users to start upgrading their setups sooner than later as most systems should work these days with JavaScript modules and at some point we won't bother with chai@4. Most new work is also not being backported to chai@4 _and_ all this work is on a volunteer bases. The best way to solve issues is to file Pull Requests to fix issues rather than issues :)

**Comment by danny0838** [comment]
@koddsson Checking the history, it seems that in versions above `4.3.8`, the line `exports.version = '4.3.8';` have not been updated. Is this normal?
