### ISSUE TITLE
Provide friendly error message when deep equality check fails because object has property value of undefined

### ISSUE THREAD

**Issue by OliverJAsh** [chaijs/chai#304]
``` js
expect({ foo: 'bar', baz: { asda: undefined } }).to.eql({ foo: 'bar', baz: {} });
```

```
AssertionError: expected { Object (foo, baz) } to deeply equal { foo: 'bar', baz: {} }
```

That's not helpful. This can be fixed by setting `chai.config.truncateThreshold = 0;`.

```
AssertionError: expected { foo: 'bar', baz: { asda: undefined } } to deeply equal { foo: 'bar', baz: {} }
```

Would it be better if we showed a diff to the user? This way, the error is clear to the user immediately (no Chai config required):

```
      AssertionError: expected { Object (foo, baz) } to deeply equal { foo: 'bar', baz: {} }
      + expected - actual

       {
         "foo": "bar"
      +  "baz": {
      +    "asda": undefined
      +  }
      -  "baz": {}
       }
```

**Comment by ahamid** [comment]
I have easily lost hours debugging the difference between two objects that appear identical (for some reason Mocha also hangs in this case so it's hard to tell which test is even failing).  It would be great if this discrepancy is somehow indicated.

**Comment by keithamus** [comment]
Thanks for your comments @ahamid, and bringing light to this (quite old) issue. A couple of points on this:

 - Diffing is the responsibility of the assertion library, because it's reporter based. For example a CLI reporter might use color escape codes while an HTML reporter uses HTML tags. Currently Mocha's HTML reporter doesn't show diffs, see mochajs/mocha#1348 for more.
 - The single line error message (`AssertionError: expected...`) uses [loupe](https://github.com/chaijs/loupe) (well, it actually doesn't just yet, but we're working on it) to pretty print objects. Without loupe the message would say something like `AssertionError: expected [object Object] to equal [object Object]`. Loupe converts the `[object Object]` bits into useful strings about an object - but it is truncated to make sure that the error message is still reasonably a single liner.
 - Loupe has no diffing logic, because it only inspects one object at a time; one separate call for `expected`, and one for `actual`.
 - Loupe's truncation logic can be controlled with `chai.config.truncateThreshold` - this defines how "shallow" or "deep" the pretty-printed value is coming out from loupe; this can be helpful in noticing object discrepancies. Currently if you get stuck, running `chai.config.truncateThreshold = Infinity` would be a quick way to dive deeper.
 - The _real_ problem here is that loupe doesn't have diffing logic, because it is passed one object at a time.
 - The _real_ solution here would be to provide loupe with enough data that it could point out the discrepancies in an object easier, for example instead of `AssertionError: expected { Object (foo, baz) } to deeply equal { foo: 'bar', baz: {} }` we could have something like `AssertionError: expected { baz: { asda: undefined }... } to deeply equal { baz: {}... }`.


If we can get Loupe doing more interesting inspection, by passing it comparison objects, then this would solve this problem without relying on the test runner's diff output, and provide much better error messages.

If anyone wants to take a stab at this I'm happy to work with/mentor them. It'd be reasonably complex, probably involve quite a bit of logic (effectively a diffing algo) but it'd be a huge improvement to error messages :smile:
