### ISSUE TITLE
.to.have.all.keys throws undefined not an object error

### ISSUE THREAD

**Issue by demisx** [chaijs/chai#368]
On http://chaijs.com/api/bdd/ under _.keys(key1, [key2], [...])_ header, the following throws `'undefined' is not an object` error:

```js
expect({ foo: 1, bar: 2 }).to.have.all.keys(['bar', 'foo']);
```

Looks like the `all` property no longer exists and it should be this instead:

```js
expect({ foo: 1, bar: 2 }).to.have.keys(['bar', 'foo']);
```

The same perhaps applies to `.any` as well.

**Comment by keithamus** [comment]
@demisx thanks for the issue. This is an odd one, as `.all` _does_ exist ([L104-L119 of assertions.js](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L104-L119)).

Which version of Chai are you using? `.all` has existed since Chai 2.0.0 - are you perhaps using an older version?

**Comment by demisx** [comment]
Hmm, you are right. I am still on 1.10 due to other libs dependent on chai. Sorry for confusion.
