### ISSUE TITLE
Suggestion to add equalsIgnoreCase method to Assert

### ISSUE THREAD

**Issue by sktguha** [chaijs/chai#404]
I suggest adding an equalsIgnoreCase method to chai.assert, i.e checks if strings are equal ignoring the case
Example -

```js
chai.assert.equalsIgnoreCase("chrome","Chrome");  //should return true
chai.assert.equalsIgnoreCase("chrome","Firefox");  //should return false
```

**Comment by keithamus** [comment]
@sktguha thanks for the issue.

You could use `assert.match` - which takes a RegExp that can be case insensitive, for example:

```js
chai.assert.match("chrome", /Chrome/i);  //should return true
chai.assert.match("chrome", /Firefox/i);  //should return false
```

Alternatively just lowercase the expected string:

```js
chai.assert.equal("Chrome".toLowerCase(), "chrome");  //should return true
chai.assert.equal("cHrOme".toLowerCase(), "firefox");  //should return false
```

I'll mark this as `more-discussion-needed` - because I'd like to know if you're happy with the above solutions, or if you really think we need your suggested assertion.

**Comment by sktguha** [comment]
Hi,
Thanks for writing back. Actually yes, I used the lowercase method to solve the problem.
 I suppose adding the method makes the code cleaner and easier to understand ? I really cannot think of more reasons why this method should be added
Thanks

**Comment by keithamus** [comment]
@sktguha I'm going to close this as a thing we won't fix, and here are my justifications:

1. Almost all of our assertions are "generic" in that they work with multiple types. Very few assertions deal with a specific type (admittedly, we do have some, like `isBelow` which only deals with numbers). This assertions feels too specific to strings. 

2. [chai-strings](http://chaijs.com/plugins/chai-string) exists as a plugin which offers much of this functionality (plus more) and is specifically tailored to strings. This is a good thing - the point of plugins is to hone down edge cases to tailor the suite to your needs.

3. Because there is a plugin which already offers this behaviour - it is best for us avoiding overlapping the functionality of that plugin. While we obviously can't always assure that we're doing that, but in this case chai-strings has `assert.equalIgnoreCase` - which we can be pretty sure we'd be overlapping functionality with.

Hopefully this gives you some good context on why I'm closing this. I'd suggest if you want to, feel free to use the above suggestions, or load [chai-strings](http://chaijs.com/plugins/chai-string) if you are facing this a lot of the time.

**Comment by sktguha** [comment]
Hi,
That was very helpful. Yes I agree with you. It is unnecessary to duplicate what already exists as a plugin. Thanks for providing a detailed explanation
