### ISSUE TITLE
Call `toString()` on function passed to `satisfy`

### ISSUE THREAD

**Issue by paulyoung** [chaijs/chai#435]
This would be much more useful than `expected ... to satisfy [Function]`

**Comment by keithamus** [comment]
Hey @paulyoung thanks for the issue.

I think you may be much better off using the message parameter (second param) of the `.satisfy()` assertion - which gives you a much more fined grained way to detail more explicit assertions. You can use it like so:

```js
expect(1).to.satisfy(function(num) { return num > 1; }, 'num > 1');
AssertionError: num > 1: expected 1 to satisfy [Function]
```

Of course, you could also use this param to set the function.toString() value, like so:

```js
x = function(num) { return num > 1; }
expect(1).to.satisfy(x, x.toString());
AssertionError: function (num) { return num > 1; }: expected 1 to satisfy [Function]
```

Of course, the design of the message param is to give you the ability to write prose, rather than more cryptic syntaxes, so this might be better:

```js
expect(1).to.satisfy(function(num) { return num > 1; }, 'number should be above one');
AssertionError: number should be above 1: expected 1 to satisfy [Function]
```

I'll close this - because for one *I feel* like the message feature will solve your problem, and for two I feel like stringifying functions could result in far messier assertion errors. However if you feel really strong about this, please feel free to comment and I'll re-open it for debate.

**Comment by paulyoung** [comment]
In my case the function I was passing to `satisfy` was coming from elsewhere so I had no context of what the error should be.

I've moved to a different approach now anyway for other reasons but suppose I could always create a plugin if I ever needed this behavior in future.

Happy to keep this closed. Thanks @keithamus!
