### ISSUE TITLE
chai can't cope with AssertionErrors raised from node's assert

### ISSUE THREAD

**Issue by danielbprice** [chaijs/chai#442]
I'm opening a new issue for the problem described in
https://github.com/chaijs/chai/issues/206#issuecomment-33762758

Here is a sample coffeescript program which illustrates this problem:

```coffeescript
node_assert = require("assert")
chai = require("chai")

expect = chai.expect

foo = () ->
    node_assert("blue" is "red")

expect(() -> foo()).to.throw(node_assert.AssertionError)
```

When run this produces:

```
TypeError: Cannot read property 'actual' of undefined
  at new AssertionError (assert.js:42:24)
  at Assertion.assertThrows (/t/node_modules/chai/lib/chai/core/assertions.js:1052:17)
  at Assertion.ctx.(anonymous function) [as throw] (/t/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
  at Object.<anonymous> (/t/foo.coffee:10:1)
  at Object.<anonymous> (/t/foo.coffee:2:1)
  at Module._compile (module.js:456:26)
```

However, I would expect this to pass properly.  Please see the referenced comment from
@freeformsystems for some investigation into why this is happening.  He also proposed a fix
there, as well.

**Comment by keithamus** [comment]
The fix is a little too specific for me. 

I think a much simpler fix for this would be to simply drop the XOR assignment to `name`. So where we set name ([assertion.js#L1219-1222](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L1219-L1222)) we currently have

```js
      name = constructor.prototype.name || constructor.name;
      if (name === 'Error' && constructor !== Error) {
        name = (new constructor()).name;
      }
```

which could become

```
      name = constructor.prototype.name;
      if (!name || (name === 'Error' && constructor !== Error)) {
        name = constructor.name || (new constructor()).name;
      }
```

This solves the specific problem you want to address, while also keeping away from requiring in Node's assert, meaning browser friendliness :smile:.

Happy to see a PR for this (with some tests to back it up of course).

**Comment by danielbprice** [comment]
@keithamus, I can confirm that the fix you designed works perfectly for this case.  I applied it and then tried to invent some test cases for it, but we're a little too deep into javascript innards that I don't feel familiar with.  I tried building out my own class called AssertionError but I couldn't get it to trip in the same manner as node's AssertionError.

**Comment by keithamus** [comment]
@danielbprice if you set up a PR with what you have, and then we can both go through the PR and add some more tests to it :smile:

**Comment by freeformsystems** [comment]
Happy to see this being addressed and glad you have a better fix :) Thanks.

**Comment by kmudrick** [comment]
Is the fix that @danielbprice made going to get merged in any time soon?

**Comment by freeformsystems** [comment]
If you think about this the error is actually to do with calling `new constructor()` without knowing the constructor implementation (ie, arguments and argument validation), therefore this problem could easily happen again with other Error implementations.

If it is not sufficient to just use the `name` field directly and there is a case where `new constructor()` is required then it should go in a try/catch I think and a default name used or an error thrown that is more indicative of the actual problem (Could not instantiate Error class).

Personally I would remove the call to `new constructor()` and document that Error subclasses should supply a `name` field otherwise Error is used which may not be indicative of the class, just some more thoughts on the issue.
