### ISSUE TITLE
chained property tests fail

### ISSUE THREAD

**Issue by cappslock** [chaijs/chai#443]
If I do this:
```js
var expect = require('chai').expect;

var dogs = {
    cat: 'a',
    rat: 'b'
};

expect(dogs).to.be.an('object')
    .and.have.property('cat')
    .and.have.property('rat');
```
This happens:
```
AssertionError: expected 'a' to have a property 'rat'
```

**Comment by keithamus** [comment]
Hi @cappslock thanks for the issue.

`.property()` changes the subject of the assertion, so you can make additional assertions on the property - [as described by the documentation](http://chaijs.com/api/bdd/#-property-name-value-); to quote:

> Furthermore, property changes the subject of the assertion to be the value of that property from the original object. This permits for further chainable assertions on that property.

>  ```js
expect(obj).to.have.property('foo')
  .that.is.a('string');
expect(deepObj).to.have.property('green')
  .that.is.an('object')
  .that.deep.equals({ tea: 'matcha' });
expect(deepObj).to.have.property('teas')
  .that.is.an('array')
  .with.deep.property('[2]')
    .that.deep.equals({ tea: 'konacha' });
  ```

So this is expected behaviour. You want to have the following instead:

```js
var expect = require('chai').expect;

var dogs = {
    cat: 'a',
    rat: 'b'
};

expect(dogs).to.be.an('object')
    .and.have.property('cat');
expect(dogs)
    .and.have.property('rat');

//alternatively:

expect(dogs).to.be.an('object');
    .and.include.keys('cat', 'rat');
```

I'm going to close this issue - but let me know if your problem isn't resolved and we'll re-open it and discuss it more. Otherwise feel free to file a new issue.

**Comment by cappslock** [comment]
Makes sense. Thanks!
