### ISSUE TITLE
Could `match` check for captures?

### ISSUE THREAD

**Issue by johngeorgewright** [chaijs/chai#447]
Would you consider extending the `match` test to test for captures too?

Ie, unless there's a better way of doing it, I'm currently writing:

```javascript
var regexp = /some (\w+) to test/;
expect('some thing to test').to.match(regexp);
expect('some thing to test'.match(regexp)[1]).to.equal('thing');
```

Could there be some kind of syntax that does both?

```javascript
expect('some thing to test').to.match(/some (\w+) to test/).and.capture(0).equals('thing');
```

**Comment by keithamus** [comment]
Hey @johngeorgewright thanks for the issue.

How you're currently doing it is probably the best way - at the moment `expect().match()` does not give you back the RegExp, and so you're right, you cannot assert on the matches after this.

There is an alternative way you could use - but its a bit of a hack. There is a non-standard feature (but supported in all browsers) of the `RegExp` constructor: [it has `$1`, `$2`, `$3` ... `$9` properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/n). When you do a `.match` or `.exec` that has a match group - RegExp will assign these, meaning you could also do the following in your code:

```js
var regexp = /some (\w+) to test/;
expect('some thing to test').to.match(regexp);
expect(RegExp.$1).to.equal('thing');
```

We could make it so that `expect().match` returns the result of `re.exec`, but that would be a breaking change, so would need to go into the `3.x.x` branch. Or we could add a `capture()` method as you suggest. Both of these seem a too much to me - perhaps the real solution is to have a Chai-Regexp plugin which does much more advanced regex property matching?

**Comment by johngeorgewright** [comment]
Thanks for the reply @keithamus.

The `$1, $2...` properties is an interesting idea, but I'm unsure it would go down too well with some of the people I work with if it's non-standard. Good to know though.

A plugin isn't a bad idea I supposed. Maybe I'll have a go... it would be good for me to get to know your plugin API.

**Comment by keithamus** [comment]
Plugins are really easy and super fun to build, we have a pretty comprehensive guide and tutorial on how to write them on the website; see [building a helper](http://chaijs.com/guide/helpers/) and [plugin core concepts](http://chaijs.com/guide/plugins/) pages.

**Comment by johngeorgewright** [comment]
The beginning: https://github.com/johngeorgewright/chai-match

**Comment by keithamus** [comment]
Sweet! You should add it to [the website plugins list](https://github.com/chaijs/chai-docs/blob/master/plugins.js) and it'll appear here; http://chaijs.com/plugins.

I'll close this as it looks like you're nailing it :smile:
