### ISSUE TITLE
ChaiJs in-browser testing doesn't seem to work on pages using requireJs

### ISSUE THREAD

**Issue by RavenHursT** [chaijs/chai#448]
I have a page that's using requireJs and chai's initialization code isn't attaching ```window.chai```:

```javascript
if (typeof exports == "object") {
  module.exports = require("chai");
} else if (typeof define == "function" && define.amd) {
  define("chai", [], function(){ return require("chai"); });
} else {
  (this || window)["chai"] = require("chai");
}
```

injecting chaiJs into other pages w/o require, ```window.chai``` is available just fine.  Is there a workaround here?

**Comment by RavenHursT** [comment]
So.. I worked around it this way:

```javascript
                    page.evaluate(function(){
                            require(['chai'], function(chai){
                                window.callPhantom(chai.version);
                                window.chai = chai;
                            });
                    }, function(){
                        done();
                    });
```

For obvious reasons, this is not exactly desirable because of the asyncronous execution that needs to be handled here now.  Is there any possible way that chaiJs could handle this usecase for us so that this could be simplified?

**Comment by csnover** [comment]
Modules aren’t supposed to pollute the global scope so the current behaviour is correct. If you are using a module loader you should always be loading Chai through the module loader. If you want to expose Chai globally then either continue doing what you are doing or load it before you load a module loader.

**Comment by RavenHursT** [comment]
Well.. that works fine if the pages that you're looking to inject chai into are your own and you know that you'll always have a module loader on the page.  But what we're doing is loading multiple different client pages and running tests on them.  Some pages may or may not have a module loader on them.

I noticed that chai attempts to handle the presence of a module loader (ie. require() when running in node vs just in the window of a browser w/o a module loader). But the following block of code doesn't account for webpages that have a module loader running in them:

https://github.com/chaijs/chai/blob/master/chai.js#L5423

**Comment by csnover** [comment]
If you’re injecting Chai yourself into some unknown, untrusted page so you can use it, you should also be able to either temporarily undefine `define` yourself, or check for it yourself at the same time and change the way you load stuff.

Now, that said, I don’t know exactly what you are trying to accomplish, but my gut says injecting your code into someone else’s page so you can run tests isn’t a very good idea. You’re bound to run into more collisions and other issues like this. Intern’s [functional testing](https://theintern.github.io/intern/#writing-functional-test) is a better idea, since it allows you to pull data safely off of a page from a test system where you can then run your Chai assertions in a known stable environment.

With regards to the line you are referring to, that is a UMD signature. It comes from the build system (component) and is going to look exactly the same whether it’s built with component or browserify or any other build system that outputs a UMD file. That code is not part of Chai’s code. It also does indeed account for pages with a module loader, as that is the entire point of UMD: work with module loaders and fall back to globals if a module loader isn’t in use.

**Comment by RavenHursT** [comment]
Ok.. I see your point now.  Yeah.. we're doing functional testing of different pages created by our SaaS app for different clients who are creating their own page templates.  Thanks for the breadcrumb to intern.. looks very useful.
