### ISSUE TITLE
Convenient Fail

### ISSUE THREAD

**Issue by Waog** [chaijs/chai#449]
Currently it's pretty cumbersome to make chai fail. I'd appreciate some simple short methods to fail a test. For example:
```javascript
assert.fail();
assert.fail("some reason");
expect().toFail();
expect("some reason").toFail();
```

**Comment by keithamus** [comment]
Hey @Waog thanks for the issue.

The good news is we have methods for that! `assert.fail()` has existed for a long time, and since [`2.1.0`](https://github.com/chaijs/chai/releases/tag/2.1.0), thanks to @Soviut, we have [`expect.fail()`](https://github.com/chaijs/chai/blob/master/lib/chai/interface/expect.js#L25-L33) and [`should.fail()`](https://github.com/chaijs/chai/blob/master/lib/chai/interface/should.js#L41-L61). All take the signature of `actual, expected, [message, [operator]]`, so the following will work:

```js
chai.assert.fail(1, 2, 'some reason');
chai.expect.fail(1, 2, 'some reason');
var should = chai.should();
should.fail(1, 2, 'some reason');
```

Unfortunately they're not documented on the website yet - the website is changing quite a bit and they'll be up there soon!

I'll close this for now, but let me know if this is still a problem for you and I can re-open it, or you can file a new issue. :smile:

**Comment by keithamus** [comment]
Also, if you want to fail a test - you can always just throw an error - Mocha and many other test runners will fail on any error, e.g:

```js
it('throws', function () {
  throw new Error('some reason');
});
```

**Comment by Waog** [comment]
Thanks for your answer. Yes, I recognized the solution with throwing a custom Error shortly after posting.

The fail method you mentioned above is in fact well documented, and I knew about it. But I have some cases where I don't have any expected or actual values, the only reason for failing is passing a certain point in control flow.

For example I have a Mockobject with a method which should not be called. My desired way of implementing it would be, to write `chai.assert.fail('this method should never be called');` into the stub-method.

Instead I have to write some cumbersome code, by evaluating how often the method was called and compare it to an expected value.

This is not really a big issue for me, I can also go with throwing custom errors. Just wanted to give you some feedback :)

**Comment by keithamus** [comment]
Ok @Waog, I've got one last idea for you then:

You can access the raw `AssertionError` class which is a property of the `chai` object, and this allows you to throw your own AssertionErrors:

```js
var chai = require('chai');
var AssertionError = chai.AssertionError;

throw new AssertionError('foo');

// It's the same error class thai chai throws:
expect(function () { chai.expect('foo').to.equal('bar') }).to.throw(AssertionError);
```

**Comment by Waog** [comment]
Ah nice, I'll try that ☺
