### ISSUE TITLE
failed to use in duojs

### ISSUE THREAD

**Issue by rogerz** [chaijs/chai#463]
I'm using chai in [duojs](http://duojs.org).

It was OK on chai@2.3.0 but fails on chai@3.0.0. I made a minimum project to reproduce the issue

```
$ make test
duo --root . --type js --stdout < test/tests.js > build.js
     building : from stdin
        using : compatibility
        using : stoj
    installed : chaijs-chai@3.0.0
        built : from stdin
Error: cannot find module "assertion-error"
  url: http://localhost:36682/build.js
  lineno: 20
```
See https://github.com/rogerz/duo-chai

**Comment by rogerz** [comment]
It seems to break since https://github.com/chaijs/chai/commit/afc8aa1d5039db37c5a07e7cc6bde6300261aae9 in which component-build is replaced by browserify

**Comment by keithamus** [comment]
Hey @rogerz thanks for the issue.

Our main areas of compatibility are with both npm and bower. We don't support other package managers because of the maintenance burden (see #353 asking for JSPM support).

The npm package lists its dependencies in the `package.json` - if duojs is unable to read that and install its dependencies, then I imagine that's duojs' issue I'm afraid. For bower, we also include the `chai.js` file which is a fully compiled file (compiled with browserify). duojs should be able to cope with that - as it's a drop in script that you could put into a `<script>` tag - to use it I imagine you'd need to do `require('./chai/chai.js')` although I'm not sure of the workings of duojs.

I'm going to close this - because as stated we don't support other package managers. If you need any more help with your issue though, I'm happy to help where I can. Just comment in this issue or raise a new one as you see fit :smile:
