### ISSUE TITLE
Are .increase, .decrease and .change really chainable ?

### ISSUE THREAD

**Issue by olivr70** [chaijs/chai#497]
**.increase**, **.decrease** and **.change** methods and their aliases are added to Assertion using **addChainableMethod**.

All the documentation and the tests present them as simple methods (which should probably be added with **addMethod**).

Being very new to Chai, I am not sure of the implications of such a change, which would probably be a breaking one.

**Comment by keithamus** [comment]
Hey @olivr70 sorry it's taken so long to reply to this - this one slipped through my notifications net.

I don't think it matters that much that we've used `addChainableMethod` over `addMethod`. The real difference is that `addMethod` does less work because it doesn't have to set up the chain.

So I guess I'm saying - if you want to you _could_ change them, but there's very little point in doing so.

I'll close this issue for now, but if you feel strongly about changing them let me know and I can re-open it and we can work together on making a PR for this :smile:
