### ISSUE TITLE
isObject fails on window.performance.timing

### ISSUE THREAD

**Issue by TheSavior** [chaijs/chai#504]
In the browser, when calling typeof on [window.performance.timing](https://developer.mozilla.org/en-US/docs/Web/API/Performance/timing)...

```
>typeof(window.performance.timing)
"object"
```

When calling chai's getType(window.performance.timing):

```
>getType(window.performance.timing)
"performancetiming"
```

Because
```
var timing = window.performance.timing;
var type = Object.prototype.toString.call(timing);
"[object PerformanceTiming]"
```

This took me a long time to track down why 
```
// this worked:
assert.isTrue(typeof(timing) === 'object');

// and these didn't
assert.isObject(timing);
assert.typeOf(timing, 'object');
```

I'm not sure what the correct solution here is, but there should probably be a way to test this as I expected originally.

**Comment by keithamus** [comment]
Hey @TheSavior thanks for the issue.

As of [chai 3.0.0](https://github.com/chaijs/chai/releases/tag/3.0.0) we have switched to using [`toStringTag`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString) types because they are much more helpful for ES6 types, such as Symbols, Promises and TypedArrays. In fact our [docs suggest that we use toStringTags to determine this](http://chaijs.com/api/assert/#isObject-section)

More fundamentally, why are you asserting that window.performance.timing is an object? Why not just `assert.ok`? Do you _actually care_ that it is an object?

**Comment by TheSavior** [comment]
That sounds fine. We were asserting that it was an object because we didn't have another way to verify what it was and the function that was using it uses `Object.keys` so it being an object was really all we cared about. 

Having the ability to assert the type based on the string tag for ES6 stuff sounds really nice. I do wonder if that is going to be intuitive for other people. It's probably too late since chai 3.0.0 already made the change, but I could imagine it making sense to have something like `assert.tagTypeOf` and keeping the other assertions obvious. *shrug*

Thanks for clearing this up for me.

**Comment by keithamus** [comment]
I think using the `toStringTag` is much clearer than what we had before (which was a custom inspection type of thing), and obviously has more flexibility than the `typeof` which is pretty limiting, as it only checks primitives and otherwise returns `'object'`.

I agree that it doesn't make the most sense for `.isObject` - which we could potentially change to just detect `typeof obj === 'object'`. Buuut as it's clear from the docs what happens, I'd like to avoid changing things up too much like this, and they can have a habit of going back and forth a bit. So I'll close this issue for now, and if you feel strongly about it we can discuss it further :smile:.

**Comment by gdelmas** [comment]
i must concur with @TheSavior: it is very strange `isObject` does not recognize objects in the browser, when `.toString()` returns the objects name. please at least make this more obvious in the documentation.

**Comment by keithamus** [comment]
It seems like a simple thing to say "this thing is an object" but because of JavaScript's nature of "everything in an object" its a little bit ambiguous. If pushed I'd probably sooner remove `assert.isObject` than try to further specify the behaviour.

To put this another way, what do you expect should pass `.isObject`?

1. Plain objects (`assert.isObject({})`)? this seems a given
2. Should Promises `assert.isObject(Promise.resolve())`? While they're technically objects, I think some would object to labelling them as such.
3. Arrays (`assert.isObject([])`)? It would align with `typeof` (`typeof [] == 'object'`) but I'm guessing `assert.isObject([])` isn't desirable behaviour for the majority of folk?

My point is, that this boils down to three key points:

 - `typeof` is too limited for an assertion framework (this has been established because `chai.util.type` has supported a wide range of types for a long while now).
 - If we specify custom behaviour outside of `typeof` we land in some weird place where users have to read documentation of Chai to know what types are supported and what ones are not.
 - `Object#toString` works well because it gives us more types (like arrays, promises etc) and **is a behaviour defined outside of Chai**. Sure - we end up with issue like this one, but we can say "well, this is how `Object#toString` works".

**Comment by gdelmas** [comment]
hi @keithamus,

i would expect `.isObject` to match every javascript object. and not match scalar types, null's and undefined. an array and a promise are some type of object. as well as plain objects.

i would assume a developer knows what is an object in javascript. if you don't feel very confident about it, i would also conclude, that it is better to remove the assertion. it took me quite a long while to realize why `isObject` was not matching objects.

for plain objects might want to introduce something like `assert.isPlainObject()`. it would make things more obvious.

**Comment by keithamus** [comment]
I'll point out that the [docs do state](http://chaijs.com/api/assert/#-isobject-value-message-) that it uses `Object.prototype.toString`:

> Asserts that value is an object (as revealed by `Object.prototype.toString`).

I think having an `isPlainObject` would be a good idea, and perhaps ditching `isObject` at the same time. Effectively just renaming the method to make things clearer.

I think for now, if you want to use `typeof` you could simply call `assert.equal(typeof foo, 'object);`. Perhaps we can work on introducing `typeof` functionality in some other assertions at some point in the future.

**Comment by gdelmas** [comment]
the docs are misleading as they do not state how `Object.prototype.toString`'s return value will be used to determine if the value is an object.

    document.createElement('div').toString();
    > "[object HTMLDivElement]"

    ({}).toString();
    > "[object Object]"

    (5).toString();
    > "5"

`toString()` returns `object` for the both objects here. additionally it reports there type. `toString()` on the number `5` does not return `object`. one might assume that the `[object` part of the string might indicate an object. however the assertion matches the type part.

using `isPlainObject` would indicate that the assertion is matching the object type.

`isObject` could be replaced by `isType(obj, "HTMLDivElement")`, to make it more obvious and useful.


after having figured this out, i used your proposed `typeof` assertion.

**Comment by keithamus** [comment]
> the docs are misleading as they do not state how `Object.prototype.toString`'s return value will be used to determine if the value is an object.

Could you genuinely please make a pull request to improve our docs? If you have experienced a problem with the documentation then we need to make them better - and you're the best person to do that because of the issues you've had. Do you think you'd like to do this?

**Comment by gdelmas** [comment]
yes sure. i hope the suggested changes to the docs are fine.

thanks,
gerard
