### ISSUE TITLE
result.should.be.deep.equal not working

### ISSUE THREAD

**Issue by rodrigomaia17** [chaijs/chai#513]
I can do the same thing with expect(result).to.deep.equal, but is impossible with result.should.be.deep.equal . Is this the expected behaviour?

**Comment by keithamus** [comment]
Hi @rodrigomaia17 thanks for the issue.

Both call the exact same function, but there's a couple of caveats to `.should`:

 1. You need to make sure you call `chai.should()` so that chai can add `.should` to `Object.prototype` - this is how the should interface works, without it, should does not work - you'll get an error like `Cannot read property deep of undefined`
 2. If `result` is `null` or `undefined` you'll get an error something like `Cannot read property 'should' of null`. There's no way around this for the should api. You can add additional assertions like `should.exist(result); result.should...` but it's a lot of overhead. 

Is the error you have due to either one of these? If not, what error do you get?

**Comment by rodrigomaia17** [comment]
Hei @keithamus , thanks for the response. 

So, I'm receiving `Cannot read property 'equal' of undefined` . The weird thing is that I'm using the should syntax in the entire project, this issue happens only in this `be.deep.equal` line. 

I will try the first suggestion and let you know soon.

**Comment by keithamus** [comment]
@rodrigomaia17 if you provide the exact error you're seeing, I may be able to help further :smile:

**Comment by rodrigomaia17** [comment]
@keithamus Actually I got an error when I run `chai.should()`  saying `TypeError: object is not a function` and pointing to the `.should()` part of expression. Probably is some problem with the browserify or something like that. 

Anyway, I can run `result.to.be.eql(expected)` without problems. My problem is only in the `deep.equal` assertion. 

```javascript
var should  = require('chai').should();// this give me error  on .should()
// var should = require('chai') // this works, but gives me:  cannot ready property 'equal' of undefined
it('fail =/ ',function(){
  var expected = ['a','b'];
  var result = ['a','b'];
  "a".should.be.equal("a"); // this always works, calling should() or not
  result.should.be.deep.equal(expected); // cannot ready property 'equal' of undefined
}); 
``` 

I will close this issue because is probably an error in my environment, but if you have any ideas , please let me know (:

**Comment by keithamus** [comment]
the should error is because you're calling `chai.should()` multiple times (it's probably being called in your test bootstrap). When it runs, `chai.should` is now the assertion object (i.e. `chai.should.be.an('object')` now works). Basically don't run `chai.should()` twice.

I ran the above code on my machine and it works perfectly fine, so it suggests to me that stuff is happening in your test environment thats the problem - as you say. If I were you I'd strip out any plugins or any bootstrap code and require chai in manually, to see it working. Then slowly build up the environment back up, re-running tests after each line added to see which one ends up being the culprit.

**Comment by rodrigomaia17** [comment]
@keithamus Thanks! I will see what is happening. 

btw, thanks for the parallelshell, and for the great post "how to use npm as a build tool". I'm following it in my project, and just now realized that you wrote it! haha

**Comment by keithamus** [comment]
:hand: :wink: no problem!
