### ISSUE TITLE
Support DOMTokenList for .contains

### ISSUE THREAD

**Issue by tregusti** [chaijs/chai#523]
I'm using chai for some unit testing on DOM nodes and when I want to assert the presence of a class I would like to be able to do:

```js
expect(element).to.have.property('classList').that.contains('active');
```

This is not possible since `contains()` in chai assumes that it is working with an `Array` and hence uses `.indexOf`. `DOMTokenList` does not have that method, it has the better suited [`#contains(...)`](https://developer.mozilla.org/en/docs/Web/API/DOMTokenList) method.
As a reference, this works fine (since `attributes` is an [`NamedNodeMap`](https://developer.mozilla.org/en-US/docs/Web/API/Element/attributes)):

```js
expect(element).have.deep.property('attributes.active');
```

Personally I think that this should be included in core and not as a plugin.

As a side note, in ES7 [`Array#includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) exists and does what `DOMTokenList#contains` does. So that might be good to add too.

**Comment by keithamus** [comment]
Hey @tregusti thanks for the issue.

I feel like chai's core library should be focused solely on JavaScript (as in, core EcmaScript) and not extras like the DOM or Node or anything. Chai (in theory) caters all of JavaScript, not just web. We've achieved that nicely so far, and I personally would like to keep it that way (but as always, if the community disagrees by majority I will happily concede). If you strongly think this should be part of core, what are your counterpoints to the above?

Can I suggest, instead of this request, that you have a look at some of the awesome plugins that developers have made? They really are worthwhile using as they'll provide much more targeted functionality; for instance [chai-dom](https://github.com/nathanboktae/chai-dom/) has the following:

````js
expect(document.querySelector('main article')).to.have.class('foo');
expect(document.querySelector('main article')).to.have.attr('foo');
```

These look to be the kind of assertions you're after, but are much more expressive than a generic solution from core chai. Also, it's worth pointing out that plugins are able to overload existing assertions - so if you wanted `contains` to behave how you've suggested, you could raise an issue on the chai-dom plugin to have something like `expect(element).classList.to.contain('active')`.

Because of the above, I'm going to close this - but if you want to continue the discussion, feel free to - we can always re-open it or create a new one if this goes anywhere :smile:

**Comment by tregusti** [comment]
I thank you for the suggestions, and I can understand your point of view.

I only knew about some jquery based plugins to chai, and I was using pure DOM. I did not know about the chai-dom plugin. I will take a look.
