### ISSUE TITLE
provide replacement for true and false assertions (True, False)

### ISSUE THREAD

**Issue by bartoszkaczorek** [chaijs/chai#526]
*false* and *true* are javascript keywords and that produces errors in some javascript editors (i.e. eclipse javascript editor). Can you provide *False* and *True* assertions - that would fix the issue. Similar problem is with *instanceof* and *throw* assertions but since *instanceOf* and *Throw* also exist it is possible to use them as replacement, but there is no replacement for *true* and *false* unfortunately.

**Comment by keithamus** [comment]
Hey @bartoszkaczorek thanks for the issue.

The replacement for `.to.be.true` and `to.be.false` are `.to.equal(true)` and `.to.equal(false)`.

Having said that, I think if your editor is crashing or erroring because of `.to.be.true` you should look into why that is, and possibly file an issue with eclipse. `expect(true).to.be.true` (and `expect(foo).to.be.instanceof(Foo)`) is perfectly valid ES5 code, which means every browser/engine/editor made this decade should support it. V8, Rhino, SpiderMonkey, Chakra have all supported these syntaxes for many years.

I'm going to close this, because I don't think there is anything for us to do here really. While we could add `.to.be.True` and `.to.be.False` I don't think we need to, I think Eclipse needs to update their editor implementation. If you feel strongly otherwise, feel free to comment and we can look to reopening the issue.

**Comment by bartoszkaczorek** [comment]
I don't think *equal* is a real replacement - you could possibly replace almost any other assert with *equal* but that's not the way to do it. I like to still assert things using *true* assertion as it clearly shows that I am asserting a boolean value, which is not that obvious with *equal*. I understand that from a formal point of view *true* is completely legitimate and other tools should not complain about it, but since you have *instanceOf* and *Throw* assertions along with *instanceof* and *throw* it seems that having *True* and *False* would be just following that convention and make life easier until other tools will respect *true* and *false* code.

**Comment by keithamus** [comment]
`equal` is a very suitable replacement; `.to.be.true/false` are effectively aliases for `.to.equal(true/false)` while others like `instanceOf` use different operators/logic.

It's worth pointing out that `.Throw` and `.instanceOf` were added 3 years ago (see #7), when IE7/IE8 were popular browsers, and tests would fail on those because they don't support ES5 properly. We also don't support these browsers fully anyway, as they cannot use getters like `.to.be.true` (so having `.to.be.True` would not help this issue). Slight aside; the need for supporting IE7/8 is not really a thing any more: by January (4 months away) Microsoft won't offer any support for all but the latest version of IE.

So, while `.Throw` and `.instanceOf` fixed problems with where tests actually run in browsers, and helped many users, your request is for adding support for an editor - for which this is the first report of this kind we've received. It sounds harsh, but it'd be easier for you to just... update or change editors, than for us to release and support code to work around your (broken!) editor. Which eclipse javascript plugin are you using btw? It looks like Nodeclipse has an issue for this: Nodeclipse/nodeclipse-1#70 - so if you're using nodeclipse, I'd suggest you focus your efforts there.

I hope the above shows you why `.to.be.True` is a different addition to `.Throw`: the time and circumstances justified adding `.Throw`, the same cannot be said for `.to.be.True`.
