### ISSUE TITLE
Method assertion option

### ISSUE THREAD

**Issue by joshperry** [chaijs/chai#530]
A while ago I created a monkeypatch for chai called dirty chai. Its purpose is to change the property assertions to method-style assertions. I have users having issues figuring out how to use it properly and would like a drop-in replacement prodatakey/dirty-chai#9.

Wonder if you guys would be amiable to an integration of the patch I do in dirty-chai directly into chai behind a configuration option.

I'd be happy to do the work, just want to see if a patch would be accepted before I work on it.

**Comment by keithamus** [comment]
Hey @joshperry thanks for the issue.

If you take a look at our roadmap (#457) the plan is to eventually get to the point where chai has a range of pluggable interfaces which are generated from assertions - including a "jshint friendly" expect/should. I think this would be a better option than monkey-patching, and it'll be better for the assert style interface which doesn't get much love. Some early spitballing was made [here](https://github.com/chaijs/chai/issues/117#issuecomment-90508208) but we need to properly bikeshed out a new declarative plugin syntax that gives enough info to interface plugins to do this kind of magic. 

I'll close this one, because I think #457 shows the direction I'd rather see out of chai. If you want to discuss the ideas in #457 further, I think we should totally continue that over there.

**Comment by joshperry** [comment]
Sounds good @keithamus! Thanks for the pointers. I'll head over to 117.
