### ISSUE TITLE
No error on invalid expect?

### ISSUE THREAD

**Issue by mikkotikkanen** [chaijs/chai#531]
I just found out that, the current project that I'm working on, has some test cases which have typoed expects and to my dismay, these tests still pass.

fe. `expect(true).be.fasle;` passes with flying colors, even though it is expecting it to be something that doesn't even exist.

Isn't this something that should be fixed?

**Comment by keithamus** [comment]
Hey @mikkotikkanen thanks for the issue.

We're aware of the problem, and we're working on some solutions. Have a look at #407 which will try to throw errors if you access non-existent properties like `fasle` (it will use Proxies, so will be somewhat experimental). Also see #457 which is our general roadmap ticket, where I've glossed over the idea of having a legacy style interface which would ensure all methods have parens, so `expect(true).to.be.true` becomes `expect(true).to.be.true()`. 

I'll close this now, because of the above mentioned issues. Feel free to continue the discussion in those other issues. #407 is ready for an initial PR, so if you're comfortable with Proxies, feel free to give it a try!

**Comment by mikkotikkanen** [comment]
Kk. It would be nice if there fe. would be a switch that would force the parens to be there, so that you could opt-in to the more secure implementation of the API.
