### ISSUE TITLE
Having floatEqual in assertion library

### ISSUE THREAD

**Issue by kishore25kumar** [chaijs/chai#535]
Can there be a function called floatEqual(value, expected, leastCount, message).

**Comment by keithamus** [comment]
Hey @kishore25kumar thanks for the issue.

Have you had a look at [assert.closeTo()](http://chaijs.com/api/assert/#-closeto-actual-expected-delta-message-)? I think this might cover your use case. 

Let me know if it does, otherwise, could you further explain what you'd expect your `floatEqual` function to do please.

**Comment by kishore25kumar** [comment]
@keithamus It is sufficient. It covers my use case.

**Comment by keithamus** [comment]
Glad to hear it @kishore25kumar! Thanks for using chai :smile:
