### ISSUE TITLE
Feature proposal: 'include.members(set)' with 'any' flag

### ISSUE THREAD

**Issue by benmosher** [chaijs/chai#550]
Proposal for meaning of `any` flag with `include.members([set])`:

```js
// valid: some intersection exists
expect([1, 2, 3]).to.include.any.members([2, 5, 6]) 
// invalid: no intersection (disjoint)
expect([1, 2, 3]).to.include.any.members([4, 7, 9])
```

and conversely, with `not` flag:

```js
// valid: completely disjoint
expect([1, 2, 3]).not.to.include.any.members([4, 7, 9])
// invalid: not completely disjoint (some intersection)
expect([1, 2, 3]).not.to.include.any.members([2, 5, 6])
```

These assertions are difficult to express with `includes` alone.

If this behavior makes sense and is desired by others, I am willing to submit a PR.

**Comment by keithamus** [comment]
Hey @benmosher thanks for the issue!

We actually have a plugin to handle this, called [chai-things](https://github.com/chaijs/Chai-Things). It gives you `any` and `some`, so you can make these exact kind of assertions. If you want to include it, you can just follow the "Installation and Usage" section of the docs, to quote:

> # Installation and usage

> ```
$ npm install chai-things
```
> ```js
var chai = require("chai");
chai.should();
chai.use(require('chai-things'));
```

I'm going to close this issue, because we already have a plugin. We may one day move it into core if enough people rely on it, but it's not on the roadmap so won't be any time soon.

**Comment by benmosher** [comment]
Ah, perfect. Thanks!
