### ISSUE TITLE
Website still shows v2.1.0 as the latest -- latest is actually v3.4.2

### ISSUE THREAD

**Issue by JamesMGreene** [chaijs/chai#554]
From [chaijs.com](http://chaijs.com/): 

![image](https://cloud.githubusercontent.com/assets/417751/11213503/edade4b4-8d01-11e5-999a-65604a1f8d93.png)

From your [GitHub Releases listing](https://github.com/chaijs/chai/releases):

![image](https://cloud.githubusercontent.com/assets/417751/11213466/ce918d56-8d01-11e5-9692-6f8f7f964b2d.png)

**Comment by keithamus** [comment]
Thanks for the issue @JamesMGreene.

We're actually undergoing a big redevelopment of the site to be more automated - using Jekyll and gh-pages. You can see the progress here; https://github.com/chaijs/chai-docs/issues/74. If you want a preview of the new site, have a look at https://chaijs.github.io/chai-docs/ - it will soon have version info extracted from the github releases API and so the version number will be up to date.

Because of the above, I'm going to close this issue: TL;DR we're on it :wink:

**Comment by JamesMGreene** [comment]
:+1:
