### ISSUE TITLE
Possible to make assert(expression) show the expression itself in the error message?

### ISSUE THREAD

**Issue by manad777** [chaijs/chai#595]
Could assert(expression [,message]) be made to include the expression itself as a message if no custom message is given? Eg, if the assertion "assert(list.contains(value))" fails, instead of displaying "AssertionError Unspecified AssertionError", display "AssertionError list.contains(value)".

I'm used to C++ where macros allows you to be more "meta" and capture the expression itself as a string if you want. This doesn't seem possible with ChaiJS, since it's a straight function call, but I'm still new to Javascript so I'm hoping by asking here someone can show me I'm wrong. For example, creating my own replacement assert call which would call chai's assert with an automatic argument.

The motive is convenience. I don't think custom assert messages are necessary, assertions are a developer-oriented error indicator which speak for themselves. Filename/linenumber are an acceptable substitute but not as convenient since they require me to look them up. It's a really minor issue, to be honest.

**Comment by keithamus** [comment]
Hey @manad777 thanks for the issue!

JavaScript itself doesn't have great metaprogramming features - and most are bound to runtime introspection. If you wanted to capture an expression as a string you'd need to use a compiler, so it can translate code at compile time (which is pretty much what every other language does anyway). 

Chai's approach (and most JS test frameworks) is slightly different, because we only have runtime introspection. Instead of macros, we just provide a richer set of assertion methods. The idiomatic-Chai-way of writing `assert(list.contains(value))` would be `assert.include(list, value)` (or  `expect(list).to.include(value)` or even `list.should.include(value)`) - this way Chai has both values, and understands the operation you want to execute on them, and now can utilise runtime introspection to give you some similar results to using macros:

```js
> assert.include([1,2,3], 1)
undefined
> assert.include([1,2,3], 7)
AssertionError: expected [ 1, 2, 3 ] to include 7
```

However, if you really want to do it the C++ way, I know of two ways you can do it:

1. Write a [Babel](https://babeljs.io/) plugin. Babel is a tool to compile your JS code into new JS code (the JS community calls these "transpilers") you could hook onto the assert call and translate the argument list, so that `assert(list.contains(value))` becomes `assert(list.contains(value), 'list.contains(value)')`.

2. Find a transpiler that provides macros and write one. [Sweet.js](http://sweetjs.org/) is the most popular as far as I am aware. Something [like this Sweet.js macro](http://sweetjs.org/browser/editor.html#let%20assert%20=%20macro%20%7B%0A%0A%20%20%20%20case%20%7B%0A%20%20%20%20%20%20%20%20_%20($toks:expr)%0A%20%20%20%20%7D%20=%3E%20%7B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20var%20toks%20=%20#%7B$toks%7D;%0A%20%20%20%20%20%20%20%20var%20toks_str%20=%20unwrapSyntax(toks%5B0%5D).inner.map(function(tok)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20unwrapSyntax(tok);%0A%20%20%20%20%20%20%20%20%7D).join(%22%22);%0A%0A%20%20%20%20%20%20%20%20letstx%20$tok_str%20=%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20makeIdent('assert',%20#%7B$here%7D),%0A%20%20%20%20%20%20%20%20%20%20%20%20makeDelim('()',%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20toks%5B0%5D,%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20makePunc(',',%20#%7Bhere%7D),%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20makeValue(toks_str,%20#%7Bhere%7D)%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D,%20#%7B$here%7D)%0A%20%20%20%20%20%20%20%20%5D;%0A%20%20%20%20%20%20%20%20return%20#%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20$tok_str%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20%0A%7D%0A%0Aassert(1%20==%201);) will take an expression and pass it as a string into the second argument. Click the link to see an example.

Hopefully this answers your question well enough @manad777. I'll close this issue for now, because I think it has - but let me know if you want to discuss this further, or if you feel it is unsolved and I can re-open it. :smile:

**Comment by manad777** [comment]
Thanks for taking the time to write that extensive reply, Keith, and for pointing me in the right direction.

**Comment by keithamus** [comment]
:+1: no problem @manad777
