### ISSUE TITLE
Documentation example on negated .throw gives an error

### ISSUE THREAD

**Issue by dinostheo** [chaijs/chai#623]
I was trying some of the exception examples from the documentation http://chaijs.com/api/bdd/ about exceptions thrown and I found something that seems not to be valid.

```
'use strict';

let expect = require('chai').expect;

let err = new ReferenceError('This is a bad function.');
let fn = function () { throw err; }

describe('Test', () => {
    it ('chain the exception asserts', () => {
        expect(fn).to.throw(ReferenceError).and.not.throw(TypeError);
    });
});
```

the above code will give me the following error output:
```
AssertionError: expected [ReferenceError: This is a bad function.] to be a function
```

The code is copied from the documentation.

**Comment by keithamus** [comment]
Thanks for the issue @dinostheo.

Firstly, if your example is concrete - then you should know that as you're already asserting that `fn` has thrown a `ReferenceError`, then by design it cannot have thrown a `TypeError` - so this assertion is redundant. Regardless of that, there is an issue here. First let me explain why it works this way:

The documentation is correct - for what there is of it. Sadly we have poorly documented the way `throw()` chains inside of chai.

Function like `throw` and `property` have a chaining feature: when you assert on them, they change the context of what you're asserting on. This is really useful because they're typically functions where you're likely wanting to assert into those properties more than the original context. This is the typical behaviour we encourage:

```js
expect(fn).to.throw(ReferenceError).and.have.property('message').equal('An error');
```


To illustrate the problem you're having by combining `to.throw().and.not.throw()`:

```js
expect(fn).to.throw(ReferenceError).and.not.throw(TypeError);
//         ^         ^                                                ^
//        │       │                                              ┕ here you are now asserting on the thrown error
//        │       ┕ this changes the context to the thrown error
//        ┕ here you are setting the context to `fn`
```

The "right" way to do what you're asserting is to use one of the following instead:

```js
// Two separate assertions
expect(fn).to.throw(ReferenceError);
expect(fn).to.not.throw(TypeError);

// Or chain, but use instanceOf 
expect(fn).to.throw(ReferenceError).and.not.be.instanceOf(TypeError);

// Of course, a ReferenceError is, by design, not a TypeError - so the extra assertion is redundant
expect(fn).to.throw(ReferenceError);
```

---

So - the issue we have here is poor documentation. We should address this by making sure the docs explicitly state that this happens, much like they [do with `.property`](http://chaijs.com/api/bdd/#-property-name-value-):

> Furthermore, property changes the subject of the assertion to be the value of that property from the original object. This permits for further chainable assertions on that property.

> ```js
expect(obj).to.have.property('foo')
  .that.is.a('string');
expect(deepObj).to.have.property('green')
  .that.is.an('object')
  .that.deep.equals({ tea: 'matcha' });
expect(deepObj).to.have.property('teas')
  .that.is.an('array')
  .with.deep.property('[2]')
    .that.deep.equals({ tea: 'konacha' });
```

@dinostheo - would you like to make a PR updating the docs to reflect this? Our docs are generated from the code - so you'd need to update the comment docs [which are here (assertion.js#L1238-1272)](https://github.com/chaijs/chai/blob/039eef7f2b76aab4555bbf146b55b87b2b31110c/lib/chai/core/assertions.js#L1238-L1272). If you did update them, you'd get a place in our [hall of fame](https://github.com/chaijs/chai/graphs/contributors) :smile:

**Comment by dinostheo** [comment]
@keithamus 
Thanks for the detailed explanation. In a few paragraphs you made me understand better a tool that I use almost daily.

Btw my example was actually slightly wrong. The example in the code comment was different as you pointed on your link. Nevertheless, still wrong. 

PR is coming, hall of fame sounds good :smile:
