### ISSUE TITLE
endsWith/endWith with expect

### ISSUE THREAD

**Issue by davidolivier1337** [chaijs/chai#637]
Hi, 

I have some troubles with the `chai-string` and especially with the `endsWith/endWith` assertions.

When I want to test your samples on [your doc](http://chaijs.com/plugins/chai-string/), such as below:
`expect('abcdef').to.endsWith('def');`
I've got this error:
`TypeError: expect(...).to.endsWith is not a function`

I don't know if my sample is wrong or something else.

Thanks.

**Comment by lucasfcosta** [comment]
Hello David, this is actually a plugin and the docs are taken from the [`chai-string`](https://github.com/onechiporenko/chai-string) repository README.md file.

In order to use `chai-string` you will need to `npm install` it and then require it using, for example:

```js
var chai = require('chai');
chai.use(require('chai-string'));
```

If you have already done this would you mind showing me how you're "importing" `chai-string`?

Please let me know if you need further support :smiley:

**Comment by davidolivier1337** [comment]
Thanks to you, I understand my stupid error, currently, I'm using only the `chai` module.

I have to add the module `chai-string` within my project and use with `chai.use(require('chai-string'));`.
Sorry, for this stupid issue :smiley:.

But, I've a little question about it, what the best way between this test:

`expect('abcdef').to.endsWith('def'); `

and this test, if I don't want to use `chai-string` module:

`expect('abcdef'.endsWith('def')).to.be.true;`

Thanks again for your answer.

**Comment by lucasfcosta** [comment]
There's no such thing as a stupid question, everyone makes mistakes sometimes. :smile: 

Well, particularly, I prefer the second option, because you're using the native `endsWith` implementation, therefore it's less error prone and, as you said, you won't need to require another module for it. But that's just my opinion, stick to whatever you feel is right.

**Comment by davidolivier1337** [comment]
Thanks a lot ! You confirmed you what I thought. :smiley:

**Comment by lucasfcosta** [comment]
I'm happy to help! :+1:
