### ISSUE TITLE
Printed the same values, but apparently not the same?

### ISSUE THREAD

**Issue by krainboltgreene** [chaijs/chai#647]
See: https://travis-ci.org/lacqueristas/api/builds/118714094#L2452

Test:

``` javascript
import {describe, describe as context, it} from "mocha"
import {expect} from "chai"
import immu from "immu"
import immunize from "./index"

describe("server/stack/immunize", () => {
  context("when given state with response, request, environment keys", () => {
    const state = {
      request: {
        key1: "value1"
      },
      response: {
        key2: "value2"
      },
      environment: {
        key3: "value3"
      }
    }

    it("returns state with request, wrapped in immu", () => {
      expect(immunize(state)).to.have.property("request", immu(state.request))
    })

    it("returns state with response, wrapped in immu", () => {
      expect(immunize(state)).to.have.property("response", immu(state.response))
    })

    it("returns state with environment, unchanged", () => {
      expect(immunize(state)).to.have.property("environment", state.environment)
    })
  })
})
```

**Comment by lucasfcosta** [comment]
Hello @krainboltgreene, thanks for the issue!

The reason why the comparison fails is because the `.property` assertion does a strict comparison (it means it uses `===`) to check if the property has the expected value. This means that the object you have will always be considered different from any other object, even if you have the same key/value pairs. You can also read more about strict (`===`) comparisons in JavaScript [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness).

To fix this you could use `.deep.equal` instead of `.property`, for example:

```js
expect(immunize(state).response).to.be.deep.equal(immu(state.response));
```
Feel free to ask any further questions you want about this if you still have any doubt :smile:

**Comment by krainboltgreene** [comment]
I talked with the `immu` library owner and found a better way to test that my function worked. Thanks for the reply!
