### ISSUE TITLE
dup or difference? deep.equal() and deep.equals()

### ISSUE THREAD

**Issue by unional** [chaijs/chai#650]
https://github.com/chaijs/chai/blob/master/test/expect.js#L332
vs
https://github.com/chaijs/chai/blob/master/test/expect.js#L484

**Comment by lucasfcosta** [comment]
Hi @unional, thanks for the issue!

As you can see [here](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L500), `.equals` is just another alias for `.equal`. You could also use `.eq` and it would refer to the same assertion.

**Comment by unional** [comment]
I see. I'm porting the `chai` typings from DefinitelyTyped to `typed-typings/npm-chai`.
Seems like some them were not typed correctly.

**Comment by mlippens** [comment]
@unional that's the one problem with TypeScript: the type files are not at all checked on correctness unfortunately.

**Comment by unional** [comment]
What do you mean?

**Comment by keithamus** [comment]
@unional if you'd like, you could send a PR to chai core and we'll add ts definitions to the main package! I'm personally happy to maintain ts defs for chai.

**Comment by unional** [comment]
That would be excellent.

**Comment by lucasfcosta** [comment]
Hi @unional, thank you very much for your issue!

We're very happy to have your input on Chai and we'll definitely be adopting TypeScript in the future, but as a first class citizen this time, supporting it right out-of-the-box.

You can read more about this decision [in this link](https://github.com/chaijs/chai/pull/1119#issuecomment-395978816).

We look forward to seeing you contributing again for Chai v5! 😄 

For now, I'll close this so that we can have a clean slate to work on.
