### ISSUE TITLE
Expect deep equal object doesn't show diff when contains any Symbol

### ISSUE THREAD

**Issue by bigomega** [chaijs/chai#654]
```javascript
    expect({ 
      a: Symbol('test'),
      b: 'bar',
    }).to.deep.equal({ 
      a: 'foo', 
      b: 'bar',
    })
```
Fails but does not show the diff.
If `Symbol('test')` is replaced by `'test'`, It works
![image](https://cloud.githubusercontent.com/assets/2320747/14177211/ddcbcc1a-f772-11e5-8bbd-c5c286ed2d0f.png)

**Comment by keithamus** [comment]
Hey @bigomega thanks for the issue.

Diffs are the responsibility of the test runner (in your case I'm guessing Mocha). We provide the objects (`actual` and `expected`) wholesale to the test runner, and they diff them. You're better off filing this with Mocha.

I'll close this because it's mocha's issue, not ours. If you have any other issues you'd like to report, please don't hesitate :smile:.
