### ISSUE TITLE
Feature Request: deepIncludes for objects

### ISSUE THREAD

**Issue by TheSavior** [chaijs/chai#671]
With the addition of `includesDeepMembers`, I was dissappointed finding that it only worked for arrays.

I want to be able to do assert that object1 contains everything in object2 (but maybe more as well).

Here are some test cases to show what I mean:

```
var obj1 = {
  foo: {
    baz: 'whee' 
  },
  bar: 'baz'
};

var obj2 = {
  foo: {
    baz: 'whee' 
  }
}

var obj3 = {
  bar: 'baz'
}

var obj4 = {
  foo: {
    baz: 'whee' 
  },
  bar: 'baz'
}

var obj5 = {
  bing: {
    foo: {
      baz: 'whee' 
    }
  }
}

assert.includesDeepObject(obj1, obj2); // true
assert.includesDeepObject(obj1, obj3); // true
assert.includesDeepObject(obj1, obj4); // true
assert.includesDeepObject(obj1, {}); // true
assert.includesDeepObject(obj1, obj5); // false
```

I can't do this with chai currently, but I can do this with sinon's matchers:

```
assert(sinon.match(obj2).test(obj1)); // true
assert(sinon.match(obj3).test(obj1)); // true
// ...
assert(sinon.match(obj5).test(obj1)); // false
```

Any thoughts?

**Comment by keithamus** [comment]
Hey @TheSavior thanks for the issue.

We can certainly look to include object support for includesDeepMembers. There's some changes going on with deep-eql which will make this a bit easier to do, so maybe let's wait a few weeks before we fix this.

**Comment by Mingun** [comment]
The functionality requested in this issue is implemented in [`chai-like`](https://github.com/zation/chai-like)

**Comment by lucasfcosta** [comment]
@TheSavior, thank you very much for your issue! 😄 

As we're planning on getting a clean slate to work on for Chai v5, we have been adding tasks to our `roadmap` and [this has been mapped as one of them](https://github.com/chaijs/chai/projects/2#card-10465059). For now, as @Mingun said you can use `chai-like`.

Due to house-cleaning purposes I'll now close this.

Thanks again for your input! It's been very important for us!
