### ISSUE TITLE
Ordering of parameters in assertions

### ISSUE THREAD

**Issue by weexpectedTHIS** [chaijs/chai#679]
Why is the ordering of the parameters in an expectation such that the actual value is supplied before the expectation? It seems more intuitive to order them in the same order that the scientific method works. That would mean you construct your hypothesis (expectation) and then test your hypothesis (the actual value).

**Comment by meeber** [comment]
Do you mean like:

```js
expect(magicNum).to.equal(42); // current
expect(42).to.equal(magicNum); // alternative

expect(pets).to.have.all.keys(['cat', 'dog']); // current
expect(['cat', 'dog']).to.all.be.keysOf(pets); // alternative

expect(obj).to.be.frozen; // current
expect(true).to.be.frozenStateOf(obj); // alternative
```

If you're not comfortable with the current ordering, I bet a wrapper plugin could be written for the assertions that don't naturally support being transposed. But some of them feel awkward to me, like the last example. Maybe there's better syntax though.

**Comment by weexpectedTHIS** [comment]
I mean more like

```
assert.equal(magicNum, 42); // current
assert.equal(42, magicNum); // alternative
```

**Comment by keithamus** [comment]
Hey @weexpectedTHIS thanks for the issue!

We set the actual as the first argument, followed by the expected - because that's how almost all code is written. Strip out our API and just use standard operators:

```js
if (magicNum === 42)
```
^ this is used 90% of the time

```js
if (42 === magicNum)
```
^ this is very rarely used and has its [own name "yoda conditions"](https://en.wikipedia.org/wiki/Yoda_conditions) and [own linting rules](http://eslint.org/docs/rules/yoda)

In addition to this, our API mimicks things like the [std assert lib in node](https://nodejs.org/api/assert.html). 

Because of the above reasons, which hopefully go to prove how ingrained the argument order are - that I don't think we'll be changing any time soon - I'm going to close this issue. Feel free to continue the discussion though 😄
