### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by LandonSchropp** [chaijs/chai#706]
I'd love make use of [this change](https://github.com/chaijs/chai/issues/578) in my project. Any chance we could see a quick patch-level release for it? Thanks!

**Comment by keithamus** [comment]
Hey @LandonSchropp thanks for the issue.

We're putting our effort into releasing `4.0.0` right now, which will be out soon. It's a little difficult to release a patch just for that one change, and so I think we should continue to put our energy into releasing 4.0.0.

I'll close this issue for now - because of the above, but let me know your thoughts on this - we can re-open if need be.

**Comment by LandonSchropp** [comment]
Thanks for the quick response @keithamus! That sounds fine to me. For now, I've pointed my package to the latest commit in `master` (`"chaijs/chai#6611e1a"`). It makes me a bit nervous to do that in the long run, but if 4.0 is coming out soon then I don't think it will be an issue.
