### ISSUE TITLE
What is preferred way to test lengthOf() with relational tests?

### ISSUE THREAD

**Issue by psnider** [chaijs/chai#713]
Now that .length is deprecated,
I couldn't find the preferred way to test for: length >= 1

Where I used to write:
> expect(array).to.have.length.at.least(1)

I couldn't come up with an equivalent using .lengthOf()

So I have switched to:
> expect(array.length).to.be.at.least(1)

What is the preferred method for such tests?

**Comment by meeber** [comment]
@psnider What you had originally is fine. It's usually okay to use `.length` as part of an assertion chain.

What's being deprecated is `.length()` as a method call assertion. For example: `expect(array).to.have.length(1)`

The only time it's not safe to use `.length` as part of an assertion chain is if it immediately follows a chainable method such as `.a`. For example, this breaks because of the `.a`: `expect(array).to.have.a.length.of.at.least(1)`.

A way to make the above example not break is to use the `property` assertion: `expect(array).to.have.a.property("length").of.at.least(1)`

**Comment by meeber** [comment]
Gonna close this for bookkeeping purposes but you're welcome to post if you'd like to discuss further :D
