### ISSUE TITLE
Use of 'should.contain' raises a slow tag

### ISSUE THREAD

**Issue by akauppi** [chaijs/chai#731]
Chai has the `.should.contain(...)` construct that I was using in one of my tests. Even when the data involved is trivial, running the test gets flagged with a "72..100ms" slowness indicator.

This turns me away from using it, and I picked less-expressive but functionally equivalent alternatives.

I tried to see why Chai would behave this way but wasn't able to spot the reason. 

- My test code: https://github.com/akauppi/svg.rx.js/blob/gx/test/gx-test.js#L70-L78
- Chai code in question: https://github.com/chaijs/chai/blob/c273846593dd6cb324106f242f2933f1294523b8/lib/chai/core/assertions.js#L196-L260

The slowness is shown both when running the tests in the browser, as well as if running from command line, using Phantom.

To replicate:

```
$ git clone git@github.com:akauppi/svg.rx.js.git
$ cd svg.rx.js
$ git checkout gx
$ npm update 
$ npm test
    # and/or open test/index.html
```

Using: OS X 10.11.5, Macbook Air mid 2011 (1.8GHz Core i7), Chai 3.5.0

**Comment by keithamus** [comment]
Hey @akauppi thanks for the issue.

Do you have some ideas to fix this? It is quite slow because it does a lot of traversal, but I doubt we can make it reasonably faster in all cases. If you're after speed, making specific assertions might be the way forward.

I'll close this for now. If you can think of a way to make this faster then please let us know and we'll be happy to discuss this further.
