### ISSUE TITLE
redux-saga select with selection creators

### ISSUE THREAD

**Issue by JuHwon** [chaijs/chai#746]
Hi i am using chai to assert my unit tests in my redux application.
I got an issue where chai tells me that the objects are not the same, though if i use [expect](https://github.com/mjackson/expect) it works fine. I think this is because one property is a returned function of a function. 

I made a [fiddle](https://jsfiddle.net/juhwon/1qbvr9qu/5/) to make things clear.

Is there a way to test such a thing with chai too? I would like to stay with chai, though this is a must have for me.

**Comment by keithamus** [comment]
Hey @JuHwon thanks for the issue.

It is indeed because you have two functions - which although they have the same behaviour, are different references. There are a few "workarounds" I suppose:

  - don't deep.eql on that particular object, instead make broader assertions - e.g. that is has the right keys like `SELECT`, and run a deep.eql on the arg property.
  - create a custom helper which works with Reselect to avoid the functions. [Here's the guide for building your own helpers](http://chaijs.com/guide/helpers/)
  - wait for https://github.com/chaijs/chai/issues/644 to land and use that.

I don't think we want to change the behaviour to make two functions return true for deep equality, so this (calling .deep.equal) will likely never work.

**Comment by JuHwon** [comment]
Thanks for your answer. I've written a custom helper method for my use case.

**Comment by Neophy7e** [comment]
@JuHwon I'm running through the same issue. What did you finally chose to do, to be able to compare the two objects ?

**Comment by JuHwon** [comment]
@Neophy7e I implemented something like this:

```jsx
/**
 * Chai Plugin for testing redux saga combined with selector creator functions
 * This expectEqual is implemented like the implementation of expect (https://github.com/mjackson/expect)
 */
import { Assertion, util } from 'chai';
import whyNotStrictlyEqual from 'is-equal/why';

const whyNotEqual = (a, b) =>
  (a == b ? '' : whyNotStrictlyEqual(a, b));

const isEqual = (a, b) => whyNotEqual(a, b) === '';

Assertion.addMethod('expectEqual', function(expected, msg) {
  if (msg) {
    util.flag(this, 'message', msg);
  }
  util.expectTypes(this, ['object']);
  const actual = util.flag(this, 'object');
  this.assert(
    isEqual(actual, expected)
    , 'expected #{this} to expectEqual #{exp}\n' + whyNotStrictlyEqual(actual, expected)
    , 'expected #{this} to not expectEqual #{exp}'
    , expected
    , this._obj
    , util.flag(this, 'negate') ? true : false
  );
});
```

this is not 100% fully tested so its kinda a draft. though it worked for my use cases.

**Comment by Neophy7e** [comment]
Thank you @JuHwon :) I'll let you know if I perform changes on it to improve it
