### ISSUE TITLE
instanceof() isn't conforming to instanceof operator

### ISSUE THREAD

**Issue by neico** [chaijs/chai#753]
It would be nice not to have to rely on the instanceof operator inside my test suite, but currently that's what I'll need to use:
```javascript
 // returns "class CustomClass"
// (or should I say, the constructor returns "new Proxy( this, {...}")
const CustomClass = require( "./customclass" );
...
let Instance = new CustomClass();
// Instance.should.be.a.instanceof( CustomClass );
( Instance instanceof CustomClass ).should.be.true;
```

I'm not sure what exactly is happening inside chai, but debugging the Symbol.hasInstance function resulted in showing the actual class instance being passed on the instanceof operator, while the chai instanceof method passes it's prototype, which of course will provide different results.

After reading up on the ECMAScript standard what exactly the Symbol.hasInstance function should pass as parameter I came to the conclusion that chai should pass the object (instance) itself as well and not it's prototype (if it's even the same one, a quick test said they're not the same, probably due to should() injecting itself into the prototype)

**Comment by meeber** [comment]
Hi @neico. Could you please create a complete standalone example demonstrating the problem? I haven't been able to recreate it on my own. Thanks!

**Comment by neico** [comment]
I've created a stripped down version of what I've got on this, where it still happens: http://puu.sh/q5aTA/c8f64be526.zip

don't mind the commented out line with a(), I broke it at some point when trying to get instanceof() to work and didn't find the time to fix it yet

**Comment by meeber** [comment]
Thanks for the example. The problem is that `.should` is triggering your proxy getter and returning `Object.prototype['should']` on line 42 instead of `hObject['should']`. This of course doesn't happen in your other example when you use `.should` on the result of `(Instance instanceof CustomClass)`.

I don't think Chai can do anything about a consumer intercepting the `.should` call and returning a custom value.

My recommendation is to use the `expect` syntax instead, or I guess you could dump a `if (Key === "should") return hObject[Key];` into your proxy getter, but that would be messy.

**Comment by neico** [comment]
Yeah I tried to avoid putting any test framework specific stuff in there, but I guess I could modify the getter now that I know what should actually expects from it (might help in some other edge cases I've had...)
