### ISSUE TITLE
Suggestion: Allow assertion styles to be require'd into global scope

### ISSUE THREAD

**Issue by Alhadis** [chaijs/chai#769]
It'd be ace if Chai's assertion methods (`assert`, `expect`, `should`, etc) could be called into global scope using one `require` call:

```js
require("chai/bin/assert");
require("chai/bin/expect");
require("chai/bin/should");
```

Which would automatically run the appropriate setup:

```js
global.assert = require("chai").assert;
global.expect = require("chai").expect;
global.should = require("chai").should();
```

**Motivation:** Mocha [allows modules to be required directly](https://mochajs.org/#r---require-module-name) from a configuration file, keeping the actual specs clean of any preliminary `require`s and so forth. One could then activate `should`-style assertions by adding this line to their `mocha.opts` file:

```
--require chai/bin/should
```

I'm suggesting the `/bin/` part be used to emphasise the fact these paths will actually invoke something when called, but that's all up to you, of course. =)

**Comment by Alhadis** [comment]
(If there's a way of doing this that I'm missing, please enlighten me...)

**Comment by meeber** [comment]
@Alhadis In the upcoming Chai v4.0, you'll be able to require `chai/should`. However, it doesn't modify the global object, it just initializes `should` syntax by running `should()`.

I don't feel strongly either way about extending the functionality so that it also adds the `should` function to the global object, as well as adding similar bootstrap files for `assert` and `expect`.

On the one hand, it'd only be a small change, so why not? On the other hand, it's super easy for consumers to create their own bootstrap file to `--require` that not only registers whichever Chai assertion syntax they want but also loads any plugins as well as performs any other pre-test initialization steps.

Personally I'd be open for a PR on this provided that there were accompanying tests, and it worked across all environments (Node, browser, etc.). But gonna open it up for discussion first.

**Comment by keithamus** [comment]
I would agree with @meeber's assertion that making your own file is probably easier, especially when you start adding in other plugins and whatnot. IMO there are two main ways to use chai:

```js
// once per file:
const chai = require('chai').use(require('someplugin'));
const expect = chai.expect;
```

```js
// one single bootsrap.js file:
global.chai = require('chai').use(require('someplugin'));
global.expect = global.chai.expect;
```

While having each of these files would be a small change - we need to forget about the LOC and think about the impact. It's extra maintenance for us, and a pattern which doesn't scale (cant use plugins, or assign other globals). By not having it, we encourage users to do this stuff themselves which is a good thing because they'll use one of the above patterns and be able to scale it up.

So, IMO, we should close this.
