### ISSUE TITLE
throw() behaves unexpected with custom ES2015 errors

### ISSUE THREAD

**Issue by netzhuffle** [chaijs/chai#773]
Code sample:

```
class MyError extends Error {
  constructor(message) {
    super(message);
    this.message = message;
    this.name = 'MyError';
  }
}

function myFunction() {
  throw new MyError();
}

expect(myFunction).to.throw(MyError);
```

Expected: The test should pass.

Actual:
> AssertionError: expected [Function: myFunction] to throw 'MyError' but 'MyError' was thrown

I assume this to be a bug as the message two mentioned classes are the same.

Note that the code sample works as expected when _not_ extending Error:

```
class MyError {
  constructor(message) {
    this.message = message;
    this.name = 'MyError';
  }
}
```

**Comment by lucasfcosta** [comment]
Hi @netzhuffle, thanks for the issue!
Which version of Chai are you using?
We've done a big refactor of the `throws` assertion for `4.0.0`, I also looked at the code on the `3.5.0` tag and I couldn't see why your code could be failing, since it should be falling into the correct if/else branches according to what NodeJS console showed me.

I also tested the exact same code you provided on my machine and it seems to work fine. It even breaks when I comment the line which throws the error (as expected), therefore I conclude you are not using the latest released version (`3.5.0`).

Please let me know if you still have this issue after updating to the latest released version.
Thanks again for getting in touch :smile:

**Comment by netzhuffle** [comment]
Thanks @lucasfcosta! I’m using Chai `3.5.0`.

But: I completely overlooked that I used babel whose transform-es2015-classes plugin is not compatible with chai’s `throws` (as it wraps classes in functions). So this is not a bug but an incompatibility.

Thanks for your help!

**Comment by eddyerburgh** [comment]
This issue isn't resolved. I can replicate this in node without babel.

Running node 6.9.1

```
class CustomError extends Error {}

function throwError() {
    throw new CustomError('custom error');
}

it('Throws a custom error', () => {
    expect(throwError()).to.throw(errorTypes.CustomError);
});
```
Output: 
```
Error: custom error
```

This is my workaround : 
```
it('Throws a custom error', () => {
    Promise.resolve()
        .then(() => (throwError()))
        .then(() => {
            throw new Error('Should not resolve with invalid duration');
        })
        .catch((err) => {
            expect(err).to.be.a.instanceOf(CustomError);
        });
});
```

I'm willing to take a look at this and get a PR.

**Comment by meeber** [comment]
Hi @eddyerburgh. In your example, you need to pass the function reference `throwError` to `expect` instead of invoking the function with `throwError()`. We recently updated the docs [here](https://github.com/chaijs/chai/blob/b7ff1446a7fc63ee99c4b7bfd8d71fe27b087f45/lib/chai/core/assertions.js#L1578-L1585) to make this clearer, but it hasn't been pushed to the website yet.
