### ISSUE TITLE
Suggestion: Permit aliases when registering plugin names

### ISSUE THREAD

**Issue by Alhadis** [chaijs/chai#780]
It'd be nice if `.addMethod` (and its kin) allowed an array of names to be passed instead of a string, pertaining to different aliases for the same method. For example:

```js
Chai.Assertion.addMethod(["class", "classes"], function(...classNames){
```

Which would be equivalent to doing this:

```js
function checkClassList(...classNames){ … }

Chai.Assertion.addMethod("classes", checkClassList);
Chai.Assertion.addMethod("class", checkClassList);
```

Or this:
```js
for(const name of ["class", "classes"])
	Chai.Assertion.addMethod(name, function(...classNames){
```
Which is far more cumbersome to write.

(This went through my head as I was [adding this](https://github.com/Alhadis/Atom-Mocha/commit/24ad3a82f22c0e42e7a162e721651cdef8deb076)).

**Comment by lucasfcosta** [comment]
Hi @Alhadis, thanks for your suggestion!

It seems like a good idea, although it's not essential since it's really simple to add more methods or properties (as you can see [here](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L214), for example.

It's always good to avoid code repetition, so I agree with your suggestion.

Let's just wait to hear from @keithamus and @meeber (anyone else is also invited to share their thoughts on this matter!).

Thanks again for getting in touch and wanting to improve Chai! 😄

**Comment by keithamus** [comment]
@Alhadis thanks for the great suggestion. If you want to, you could take a look at https://github.com/chaijs/chai/issues/585 - where we're having a discussion about a major overhaul of the Chai plugin system to make it much easier to develop chai plugins. We'd love to get your feedback there.

In the meantime I'll close this issue - https://github.com/chaijs/chai/issues/585 covers it, as well as many other things - I really would like to focus the discussion https://github.com/chaijs/chai/issues/585.
