### ISSUE TITLE
Advice using chai in another context

### ISSUE THREAD

**Issue by soundstep** [chaijs/chai#838]
Hi,
Sorry this is not an issue, more of a question.
Please redirect me if there is a better place.
I'd like to use chai in another context than testing. It would be very appropriate for me to use chai assert inside builder pattern classes that generates some output.
If I use:
```
chai.assert.equal(0, 1);
```
It will either do nothing or throw an ```AssertionError```.
Is there any way to use/configure chai to return me a boolean instead?
Like:
```
if (chai.assert.equal(0, 1)) {
    // do something
}
```
Thanks for any help.

**Comment by keithamus** [comment]
Hey @soundstep thanks for the issue.

We've had an issue like this before: #346. I'll quote a couple of things from there, to start with:

> Well, chai's primary focus is around testing - and so it doesn't focus on what is important in a frontend or backend library that is production ready. To expand on this, chai's concerns are:

> - Compatibility with test runners (which means throwing errors instead of returning values
- Lots of Assertions for testing behaviours of functions and exact equality (so things like `.eql`, `.deep.equal`, `.throws` and `.satisfy` none of which you'll need)
- Easy to use DSL, specifically for use within a test environment (e.g. `.should` which modifies Object.prototype - which typically is a big nono in real code)

> Things we're not concerned about:

> - Compatibility with really old browsers (we don't support IE<9)
- Code size (as you mention, its 5k LOC, 121k unminified, we never package a minified version because there is no point.
- Memory usage (I'm not saying Chai is bad at memory usage or has memory leaks, but we don't go out of our way to check for these at it executes in a short lived environment).

Having said all of that, issue #346 kind of led onto #585, which loosely talks about taking the assertions out of Chai, and decoupling them from the Chai process (the DSL, raising AssertionErrors, other couplings to chai internals).

So the TL;DR of all this is: right now to do what you want, you'll have to try/catch. I wouldn't recommend doing it, but come Chai 5, or maybe Chai 6 - we should have a bunch of libs which you'll be able to pick up and use for exactly this kind of thing 😄 

I'll close this issue for now, as I think we have enough focus with #585 to somewhat solve this, but if you have any feedback for us, please feel free to comment here, or in #585, or in a new issue.
