### ISSUE TITLE
Failed 'expect' statement timing out w/Mocha & Chai

### ISSUE THREAD

**Issue by adamstelle** [chaijs/chai#842]
I'm getting unexpected timeout behavior using Mocha and Chai's 'expect' statement when a test fails.

The code:
```javascript
require('./lib/test-env.js');

const expect = require('chai').expect;
const estimateQuery = require('../lib/estimate-query-helper.js');

describe('testing auth routes', function() {
  describe('testing estimate query helper', function() {
    it('should return an average daily rate and occupancy rate', (done) => {
      estimateQuery.getEstimate()
      .then(result => {
        expect(result[0]['avg(`Average Daily Rate`)']).to.be.a('number');
        expect(result[0]['avg(`Occupancy Rate LTM`)']).to.be.a('number');
        done();
      });
    });
  });
});
```

When I run this with correct expect values, test passes w/no timeout (and I've checked to see the returned values are all correct). But when I change 'number' to (for example) 'string' on either of the statements, rather than failing and throwing 'Expected ..., Actual ..." error, it times out.

Thanks in advance for your help!

For reference, here's the function it's calling:
```javascript
exports.getEstimate = function() {
  debug('running estimate query against SQLdb');
  return new Promise((resolve, reject) => {
    let tries = 0;
    mysql.createConnection({
      host: '104.198.143.37',
      user: 'root',
      password: 'D0wnr1ght',
      database : 'firstdb',
    }).then(function _getEstimate(connection){
      var latLow = initLat - ((tries + 1) * 0.0042);
      var latHigh = initLat + ((tries + 1) * 0.0042);
      var lngLow = initLng - ((tries + 1) * 0.0060);
      var lngHigh = initLng + ((tries + 1) * 0.0060);
      connection.query('select count(*),avg(`Average Daily Rate`), avg(`Occupancy Rate LTM`) from `airbnb_summary` where (`airbnb_summary`.`Listing Type` = "Private room"  and `Average Daily Rate` >0 and  `Number of Bookings LTM`>4 and`airbnb_summary`.`Longitude` between '+ lngLow +' and '+ lngHigh+' AND `airbnb_summary`.`Latitude` between '+ latLow +' and '+ latHigh +' );')
      .then(rows => {
        if (tries > 10) return reject(createError(500, 'something went wrong'));
        if (rows[0]['count(*)'] < 10) return _getEstimate();
        rows.tries = tries;
        resolve(rows);
      })
      .catch(err => {
        console.error(err);
        reject(err);
      });
    });
  });
};

**Comment by vieiralucas** [comment]
Hello @adamstelle, thanks for your issue.

Mocha is giving you a timeout, because the `done` callback is never called.
When the assertion fails, a exception is throwed and the `done()` code never gets executed.

You should use mocha's built in promise support.
Instead of receiving a `done` callback you can just return the promise.

Your test should look like this:

```javascript
require('./lib/test-env.js');

const expect = require('chai').expect;
const estimateQuery = require('../lib/estimate-query-helper.js');

describe('testing auth routes', function() {
  describe('testing estimate query helper', function() {
    it('should return an average daily rate and occupancy rate', () => {
      return estimateQuery.getEstimate()
        .then(result => {
          expect(result[0]['avg(`Average Daily Rate`)']).to.be.a('number');
          expect(result[0]['avg(`Occupancy Rate LTM`)']).to.be.a('number');
        });
    });
  });
});
```

Please let me know if this solves your issue.

Thank you

**Comment by adamstelle** [comment]
Thanks VERY much Vieira, super helpful. All working as expected now!

**Comment by meeber** [comment]
@adamstelle The solution posted by @vieiralucas's is correct, but I want to clarify one thing:

Even when using the `done` syntax, a failed Chai assertion would normally cause the test to immediately fail instead of timeout, despite execution stopping before calling `done()`. The reason it doesn't in your example is because the failed assertion error is being swallowed inside the promise. If you're using Node v6.6+, you should be receiving an "UnhandledPromiseRejectionWarning".

This doesn't really have anything to do with Chai and Mocha but rather the behavior of promises. For example...

```js
Promise
.resolve()
.then(() => {
  console.log("hi");
  throw Error("STOP");
  console.log("bye");
});
```

...would output "hi" only without throwing an error or outputting "bye".

**Comment by vieiralucas** [comment]
Thanks for clarifying @meeber, that makes total sense ❤️
