### ISSUE TITLE
getVisibleText() from value=test

### ISSUE THREAD

**Issue by farouk60** [chaijs/chai#850]
I have this problem, i need to get text from value=test to compare it with exact text:
                .setFindTimeout(2000)
                .findDisplayedByXpath('id("msop-profile-form")/DIV[1]/DIV[1]/INPUT')
                .getVisibleText()
                .then(function (text) {
                    assert.strictEqual(text, 'test');
                })
                .end()

the result : 
AssertionError: expected ' ' to equal 'test'

**Comment by lucasfcosta** [comment]
Hi @farouk60, thanks for the Issue!
Well, our `strictEqual` assertion works using Node's `===` implementation, so I think this is more likely to be a problem with your selector, since the final message shows a `''` as the expected value.
To solve this you can use your browser's devtools to check if an element with that Xpath really exists and if it has text inside. If that selector exists and has text this is more likely to be a problem with the tool you are using to access that element.
Let me know if you have any further doubts and I'll help you.
Thanks :smile:

**Comment by farouk60** [comment]
i have found the solution it was a input value not a text:
   .setFindTimeout(2000)
                .findDisplayedByCssSelector('input[name="firstname"]')
                .getAttribute("placeholder")
                .then(function (text) {
                    assert.strictEqual('First name', text);
                })
                .getAttribute("value")
                .then(function (text) {
                    assert.strictEqual('test2', text);
