### ISSUE TITLE
Chai iterate over seems to be buggy

### ISSUE THREAD

**Issue by Fohlen** [chaijs/chai#908]
I am unable to test my iterable class using `chai.iterate.over` .. test cases are appended below

Following is the iterator
```js
[Symbol.iterator]() {
      let self = this; // Hacky slashy
      let position = 0;
      let childs = this.getChildNames();

      return {
        next: function() {
          if (position < childs.length) {
            position++;
            return {value: self.getChild(childs[position - 1]), done: false};
          } else {
            return {done: true};
          }
        }
      }
    }
```

```js
describe('Iterator', function() {
  describe('Node', function() {
    it('should contain a valid iterator', function() {
      let node = new Node(null, '/', 'node');
      expect(node).to.be.iterable;
    })
    it('should return zero elements for a fresh node', function() {
      let node = new Node(null, '/', 'node');
      expect(node).to.iterate.for.lengthOf(0);
    })
    it('should return 2 for a node with 2 elements', function() {
      let node = new Node(null, '/', 'node');
      node.addChild('a', 'node');
      node.addChild('b', 'node');
      expect(node).to.iterate.for.lengthOf(2);
    })
    it.only('should iterate over child elements', function() {
      let node = new Node(null, '/', 'node');
      node.addChild('a', 'node');
      let node_a = node.getChild('a');
      node.addChild('b', 'node');
      let node_b = node.getChild('b');

      expect(node).should.iterate.over([node_a, node_b]);
    })
  })
})
```

Interestingly the last test case crashes .. with
`     TypeError: Cannot read property 'iterate' of undefined`
obviously there is something wrong with the `.should` style here..

Using `expect(node).to.iterate.over(...)` bugs even more, giving me:
```js
     TypeError: iterable[Symbol.iterator] is not a function
      at slice (node_modules/chai-iterator/chai-iterator.js:313:39)
      at Assertion.<anonymous> (node_modules/chai-iterator/chai-iterator.js:40:18)
      at Assertion.<anonymous> (node_modules/chai-iterator/chai-iterator.js:263:27)
      at Assertion.ctx.(anonymous function) [as over] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Context.<anonymous> (src/tree/test/iterator_test.js:31:31)
```

**Comment by meeber** [comment]
Disclaimer: I'm not familiar with `chai-iterate`; it's a 3rd party plugin.

In your example, you mix the `expect` and `should` syntax in a single assertion, which won't work:

```js
expect(node).should.iterate.over([node_a, node_b]); // won't work, mixing assertion styles
```

Please verify the stack trace you receive when replacing `should` with `to` before we continue troubleshooting.

**Comment by Fohlen** [comment]
Following is the complete stack trace:
```
  Iterator
    Node
      1) should iterate over child elements


  0 passing (10ms)
  1 failing

  1) Iterator Node should iterate over child elements:
     TypeError: iterable[Symbol.iterator] is not a function
      at slice (node_modules/chai-iterator/chai-iterator.js:313:39)
      at Assertion.<anonymous> (node_modules/chai-iterator/chai-iterator.js:40:18)
      at Assertion.<anonymous> (node_modules/chai-iterator/chai-iterator.js:263:27)
      at Assertion.ctx.(anonymous function) [as over] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Context.<anonymous> (src/tree/test/iterator_test.js:32:31)

```

The code can as well be found [on GitHub](https://github.com/inexor-game/flex/blob/master/src/tree/test/iterator_test.js#L25)..

**Comment by meeber** [comment]
I took a look at your test and the `chai-iterator` code.

Basically, `chai-iterator` is making an assumption in its `.over` assertion that any iterable fed to it is a "well-formed iterable" (Mozilla's terminology? See [this article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator)), which means that it expects the iterator that it returns to also be an iterable. More specifically, it expects the iterator that it returns to also be an iterable that returns itself instead of a new iterable when its `@@iterator` method is called. 

Most builtin iterables are well-formed. You can observe this behavior in this stand-alone example:

```js
var myIterable = [1, 2, 3];
var myIterator = myIterable[Symbol.iterator]();

console.log(myIterator[Symbol.iterator]() === myIterator);  // true
```

If you replace `[1, 2, 3]` in the above example with your `node` object from the failing test, not only does it not return `true`, it throws a "TypeError: myIterator[Symbol.iterator] is not a function".

You can open an issue with the `chai-iterator` dev asking for support to be added for non-well-formed iterables, or you can refactor your iterables to be well-formed.

Either way, there's nothing Chai core can do about this, so gonna close this issue.
