### ISSUE TITLE
Question: Chai assertion, unable to identify property using should / expect

### ISSUE THREAD

**Issue by bipo1980** [chaijs/chai#965]
Hello: Need your help on a `chai` assertion.

I have a JSON response as shown below. I want to assert that it contains "Lastname is mandatory" only.

I tried using this statement but the error i get is `AssertionError: expected [ Array(2) ] to have a deep property '#text'`. Please help how to write this correctly. Many thanks.

**using expect**

`chai.expect(data.response.error).to.have.deep.property('#text', 'Lastname is mandatory.');`

**using should**

`data.response.error.should.have.deep.property('#text', 'Lastname is mandatory.');`

**Response JSON (data)**
```
{
    response: {
        error: [
            {
            '@id': '1000',
            '#text': 'Firstname is mandatory.'
            },
            {
            '@id': '10001',
            '#text': 'Lastname is mandatory.'
            }
        ],
        result: 
        {
            status: '0'
        }
    }
}

```

**Comment by shvaikalesh** [comment]
Hey @bipo1980, thanks for the report.

`.property` assertion does not perform array iteration. It expects direct path to property, so you can get away with

```js
.to.have.deep.property('[1].#text', 'Lastname is mandatory.')
```

I don't think that is acceptable. If you know the `@id`, you can do

```js
.to.include.deep.members([{ '@id': '10001', '#text': 'Lastname is mandatory.' }])
```

If you don't, I would rather

```js
expect(data.response.error.some(e => e['#text'] == 'Lastname is mandatory.')).to.be.true
```

Chai has no built-in way to accomplish this.

**Comment by keithamus** [comment]
Hey @bipo1980 thanks for the issue.

Hopefully @shvaikalesh's comments help you on your way to solving this, but otherwise you'd have much more success posting your question to Stack Overflow - https://stackoverflow.com/. It's a great resource full of knowledgable people who will happily take the time you help you with this. This issue tracker, however, is only monitored by less than a handful of people whose time is stretched thin.

I'm going to close this issue - because its not a bug within our code. However if you do run into any more issues that you feel could be bugs, please don't hesitate to open a new issue.  I wish you the best of luck with your work and I'm sure you'll find good resources on Stack Overflow :smile:.
