### ISSUE TITLE
Chai needs better reporting message when checking that err doesn't exist fails.

### ISSUE THREAD

**Issue by xp-vit** [chaijs/chai#968]
Let's say we expect that err should not exist:

```
should.not.exist(err);
```

When this assertion fails chai reports something similar to:
```
Uncaught AssertionError: expected { Object (name, message, ...) } to not exist
```
Which doesn't provide any clue on what went wrong.

However when using https://shouldjs.github.io/ following error reported:
```
Uncaught AssertionError: expected Error {
    code: 16837,
    driver: true,
    errmsg: 'The positional operator did not find the match needed from the query. Unexpanded update: items.$.active',
    index: 0,
    message: 'The positional operator did not find the match needed from the query. Unexpanded update: items.$.active',
    name: 'MongoError'
  } to not exist
```

**Comment by keithamus** [comment]
Thanks for the issue @xp-vit 

Messaging is something we're looking at as part of our long term roadmap (https://github.com/chaijs/chai/issues/457). We'll get much better at delivering useful messages in the coming major releases; `4.0` is right round the corner and subsequent releases from that will greatly improve messaging - including the above example.

I'll close this, just because it is something on our radar, so we're sure it'll be fixed. But feel free to continue the discussion here if you'd like - or also feel free to add your input to https://github.com/chaijs/chai/issues/457
