### ISSUE TITLE
chai.js stopped working with webpack1 out of the box

### ISSUE THREAD

**Issue by AviVahl** [chaijs/chai#985]
Due to commit 4d45c5db6ed0518d7d8227f024590a4ec5983384, chai.js now requires json-loader, which is not included in Webpack 1.

Webpack 2 has a built-in json loader, so it is not affected.

Workarounds: user can manually add json-loader to his webpack 1 configuration, or use webpack 2.

**Comment by oliviertassinari** [comment]
I had to add:
```js
          {
            test: /\.json$/,
            loader: 'json-loader',
          },
```
and
```diff
-extensions: ['.js'],
+extensions: ['.js', '.json'],
```

**Comment by vieiralucas** [comment]
This should be fixed by #986

**Comment by AviVahl** [comment]
Thank you for addressing this. 👍 I'll verify (and close the ticket) once 4.0.2 is out.

**Comment by jraller** [comment]
In `chai.js` the line `exports.version = require('../package').version;` is DRY, but it is brittle with regard to webpack and also wallabyjs.

In order to get things working with wallaby any override of webpackConfig.resolve.extensions needs to include `.json`. This is an extension of the modification suggested by @oliviertassinari.

**Comment by keithamus** [comment]
Closed via https://github.com/chaijs/chai/pull/986. We'll get a release out soon.
