### ISSUE TITLE
Changes with chai@4

### ISSUE THREAD

**Issue by perrin4869** [chaijs/chai#995]
First of all, I am not sure if this is the appropriate place to post this question, so sorry if it isn't.
I tried upgrading chai to v4, but completely broke my tests. I tried to dig into the migration guide [here](https://github.com/chaijs/chai/releases/tag/4.0.0) but unfortunately I couldn't find the relevant info. I could pin down the failure to this simple example (run with mocha@3, using `chai-as-promised` 6 or 7), which passes with `chai@3` but fails with `chai@4`:

```js
  it('should pass with chai@3 and fail with chai@4', () => {
    const err = new Error('foo');
    err.name = 'bar';
    return expect(Promise.reject(err)).to.eventually
      .be.rejectedWith(Error)
      .and.to.have.property('name', 'bar');
  });
```

Apparently chai returns the value passed to `expect` now? Is this expected behavior? How do you fix this?

(updated the example to make it more clear)

**Comment by meeber** [comment]
Morning! The example you posted works on my end with Chai@4 and
chai-as-promised@7. Are you positive chai-as-promised@6 isn't being used
somehow? Are there any other factors that might be influencing your test,
or does that example still fail for you in an otherwise empty project?
What's the exact error that occurs?

**Comment by perrin4869** [comment]
Oh, just checked, you are right, the test passes. Apparently the problem is with `dirty-chai`.

```js
const chai = require('chai');
chai.use(require('chai-as-promised'));
chai.use(require('dirty-chai'));
```

This will make the test fail...

**Comment by meeber** [comment]
Can't look at it closely until tonight at earliest but try editing
dirty-chai.js in node modules and adding "return this" after each
occurrence of "defer(this, ...)"

**Comment by perrin4869** [comment]
That fixes it!!!
Should I send a PR to `dirty-chai` then?

**Comment by meeber** [comment]
You could but the maintainer of that plugin will probably want tests too,
which will take a lot more effort, so maybe just create an issue there and
link to this one.

The root of the problem is that by default Chai@4 returns a new assertion
object (with flags xferrd over) whenever an assertion is made, but each
chai-as-promised assertion returns itself instead in order to preserve the
promiseness. In order to continue preserving that promiseness, dirty-chai
would need to do the same.
