### ISSUE TITLE
Allow function calls at end of side-effect-getter chains

### ISSUE THREAD

**Issue by shicks** [chaijs/chai#997]
Google's JS style guide [prohibits](https://google.github.io/styleguide/jsguide.html#features-classes-getters-and-setters) getters with side effects, which causes difficulty when using the "expect" style of assertions.  Allowing a `()` at the end of such chains would mitigate this issue and allow people writing in Google style to use the nicer "expect" style, rather than only being able to use the old-fashioned "assert" style.

**Comment by meeber** [comment]
@shicks There has been a lot of discussion on this issue, and one attempt to support using the getters as methods, which had to be reverted due to unexpected incompatibilities and breaking changes. Here are some of the relevant threads: https://github.com/chaijs/chai/issues/302, https://github.com/chaijs/chai/issues/371, https://github.com/chaijs/chai/issues/726#issuecomment-229401449.

The last time we discussed this issue, the opinion was that the [dirty-chai](https://github.com/prodatakey/dirty-chai) plugin is an acceptable solution for this problem.

**Comment by shicks** [comment]
Sounds good, we'll look into recommending that plugin, and hopefully someday chai core will finally move off of property assertions. Thanks for all the background!
